### PR TITLE
Move DaemonThreadFactory to internal package.

### PR DESCRIPTION
**Pull request by anuraaga**
Doesn't seem like something we need to share outside our repo.

### CODE REVIEW

**Review by bogdandrutu — COMMENTED** [review]
What is the rule about internal? Do we allow other artifacts in extensions to depend on this?

**Comment by jkwatson** [comment]
> What is the rule about internal? Do we allow other artifacts in extensions to depend on this?

Great question. My opinion is that it's ok for our own extensions to use these, but I don't feel super strongly about this.

**Comment by anuraaga** [comment]
Yeah - we decided that we expect users to use a BOM. The main reason to do so would be to share internal among artifacts :)

**Review by jkwatson — APPROVED** [review]
Thanks!

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
