### PR TITLE
Break out :exporters:common module

### PR DESCRIPTION
**Pull request by jack-berg**
Related to [comment](https://github.com/open-telemetry/opentelemetry-java/pull/4501#issuecomment-1170324564) in #4501. 

Unfortunately, we still need to keep `:exporters:otlp:common` since the serialization logic is used in  `:expoters:logging-otlp`.

### CODE REVIEW

**Comment by jkwatson** [comment]
This new module ends up being 100% internal classes, correct? Can we maybe merge it into the dependent jars at build time so we don't have to publish it?

**Comment by anuraaga** [comment]
> Can we maybe merge it into the dependent jars at build time so we don't have to publish it?

Merging would probably make sense if there is only one dependent jar, though in that case we would have inlined the code in. For multiple dependent jars, it seems tricky (rename the package when inlining for each? etc). I wouldn't make it too complex.

**Comment by jkwatson** [comment]
> > Can we maybe merge it into the dependent jars at build time so we don't have to publish it?
> 
> Merging would probably make sense if there is only one dependent jar, though in that case we would have inlined the code in. For multiple dependent jars, it seems tricky (rename the package when inlining for each? etc). I wouldn't make it too complex.

oh yeah. we'd have to repackage to match the package of what we were merging to each time. ugh.

**Comment by jkwatson** [comment]
I can't tell on github, but does this end up with overlapping package names with the module you moved stuff from? We need to make sure they both export the same package, or the 2 jars will collide if using the Java Module System.

**Comment by jack-berg** [comment]
> I can't tell on github, but does this end up with overlapping package names with the module you moved stuff from? We need to make sure they both export the same package, or the 2 jars will collide if using the Java Module System.

The package names of all the classes that where moved from `:exporters:otlp:common` to `:exporters:common` are the same as before: `io.opentelemetry.exporter.internal.*`. 

The remaining classes in `:exporters:otlp:common` are all in `io.opentelemetry.exporter.internal.otlp.*`.

**Comment by jkwatson** [comment]
> > I can't tell on github, but does this end up with overlapping package names with the module you moved stuff from? We need to make sure they both export the same package, or the 2 jars will collide if using the Java Module System.
> 
> The package names of all the classes that where moved from `:exporters:otlp:common` to `:exporters:common` are the same as before: `io.opentelemetry.exporter.internal.*`.
> 
> The remaining classes in `:exporters:otlp:common` are all in `io.opentelemetry.exporter.internal.otlp.*`.

Cool. Just wanted to make sure that our JMS users wouldn't get broken packages.

**Comment by jkwatson** [comment]
Looks like this needs some conflicts resolved, @jack-berg

**Review by jkwatson — APPROVED** [review]

**Pull request merged**
