### PR TITLE
Remove unnecessary builder for OpenTelemetry instance

### PR DESCRIPTION
**Pull request by bogdandrutu**
Every implementation should provide their own way of constructing the instance.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Agree that after removing `toBuilder` this makes a lot of sense

**Review by jkwatson — CHANGES_REQUESTED** [review]
I think we need to put a temporary hold on any changes to the SDK configuration code. We need someone to create a design document that shows the end state, so we can make sure we're all pulling in the same direction and going where we all agree we're trying to go.

**Comment by bogdandrutu** [comment]
@jkwatson this is not about SDK configuration, this is an API change. And I don't think we should require all API implementations to expose a Builder.

**Comment by jkwatson** [comment]
If we do decide to remove this, it's a breaking API change, and so we should deprecate the method for a release before we remove it.

**Comment by bogdandrutu** [comment]
Dropping this, since it was easier to recreate a new PR with deprecations.

**Pull request closed without merging**
