### PR TITLE
OT Shim: Initial import the testbed from OT.

### PR DESCRIPTION
**Pull request by carlosalberto**
Ported the effort at https://github.com/opentracing/opentracing-java/tree/master/opentracing-testbed (removing/updating related bits), and creating a temporary `InMemoryTracer`, similar to OT's `MockTracer`.

We can consider later move this `InMemoryTracer` (which is now package private, doesn't do many value checks, and exists only in the tests) as a separated component, or replace it with an in-memory exporter later on.

(Also, this `InMemoryTracer` works with `SpanData` objects ;) )

### CODE REVIEW

**Comment by carlosalberto** [comment]
Addresses part of #302

**Comment by carlosalberto** [comment]
Hey hey please review (even if on top level fashion) this one @pavolloffay @tylerbenson ;)

**Comment by pavolloffay** [comment]
I would welcome to split it into 2 separate PRs. One for the tracer and done for the testbed.

Some observations/nits:
* use `Utils.checkNotNull();` for null checks.
* ideal would be to reuse tests (or just some classes) from OT artifact. First, it would require to make changes to make them more pluggable.

**Comment by carlosalberto** [comment]
The `InMemoryTracer` will probably be gone in the future, but lets indeed separate them for the sake of importing the `testbed`.

Also, I can bring some of the OT tests, but that would also have to be in another PR ;)

**Comment by carlosalberto** [comment]
> use Utils.checkNotNull(); for null checks.

Oh, I totally forgot to clean that TODO item from my side. Time to wrap that up ;)

**Comment by bogdandrutu** [comment]
What is the status of this?

**Comment by carlosalberto** [comment]
Closed on behalf of #427

**Pull request closed without merging**
