### PR TITLE
remove LabelSet from the Instrument binding API

### PR DESCRIPTION
**Pull request by jkwatson**
more for #992

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Can you run the benchmarks before after and compare?

**Comment by jkwatson** [comment]
> Can you run the benchmarks before after and compare?

sure thing. Good idea.

**Comment by bogdandrutu** [comment]
@jkwatson I am waiting for the benchmarks here :)

**Comment by jkwatson** [comment]
Here are the "before" (i.e. on master) benchmarks that use bound counters:
image
image

**Comment by jkwatson** [comment]
And here are the same on this branch:
image
image

**Comment by jkwatson** [comment]
If anything, the benchmarks imply that getting rid of the labelset API improves performance slightly.

**Pull request merged**
