### PR TITLE
Refactoring span benchmarking as per the spec

### PR DESCRIPTION
**Pull request by srprash**
Making the following changes to span creation according to the [span configuration](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/performance-benchmark.md#span-configuration) for performance benchmarking:
- Adding a service resource
- Adding the always on sampler
- Adding a single long type attribute
- Adding an event with no attributes

The benchmark result on a m5.xlarge EC2 instance:

```shell
Benchmark                                                                         Mode  Cnt     Score     Error   Units
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread                                thrpt   10  3274.915 ±  16.454  ops/ms
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.alloc.rate                 thrpt   10   882.267 ±   3.930  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.alloc.rate.norm            thrpt   10   424.000 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.churn.G1_Eden_Space        thrpt   10   893.436 ± 102.937  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.churn.G1_Eden_Space.norm   thrpt   10   429.436 ±  51.007    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.churn.G1_Old_Gen           thrpt   10     0.001 ±   0.002  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.churn.G1_Old_Gen.norm      thrpt   10     0.001 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.count                      thrpt   10    63.000            counts
SpanBenchmark.simpleSpanStartAddEventEnd_01Thread:·gc.time                       thrpt   10    34.000                ms
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads                               thrpt   10  4865.498 ±  73.035  ops/ms
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.alloc.rate                thrpt   10  1309.461 ±  20.750  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.alloc.rate.norm           thrpt   10   424.001 ±   0.002    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.churn.G1_Eden_Space       thrpt   10  1316.544 ± 126.221  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.churn.G1_Eden_Space.norm  thrpt   10   426.263 ±  39.532    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.churn.G1_Old_Gen          thrpt   10     0.003 ±   0.002  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.churn.G1_Old_Gen.norm     thrpt   10     0.001 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.count                     thrpt   10    77.000            counts
SpanBenchmark.simpleSpanStartAddEventEnd_02Threads:·gc.time                      thrpt   10    46.000                ms
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads                               thrpt   10  6313.366 ±  50.898  ops/ms
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.alloc.rate                thrpt   10  1705.337 ±  14.369  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.alloc.rate.norm           thrpt   10   424.000 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.churn.G1_Eden_Space       thrpt   10  1704.363 ± 152.672  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.churn.G1_Eden_Space.norm  thrpt   10   423.786 ±  38.624    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.churn.G1_Old_Gen          thrpt   10     0.002 ±   0.002  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.churn.G1_Old_Gen.norm     thrpt   10     0.001 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.count                     thrpt   10    84.000            counts
SpanBenchmark.simpleSpanStartAddEventEnd_05Threads:·gc.time                      thrpt   10    63.000                ms
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads                               thrpt   10  6310.809 ± 140.526  ops/ms
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.alloc.rate                thrpt   10  1717.626 ±  41.551  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.alloc.rate.norm           thrpt   10   424.001 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.churn.G1_Eden_Space       thrpt   10  1743.940 ± 118.514  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.churn.G1_Eden_Space.norm  thrpt   10   430.611 ±  31.704    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.churn.G1_Old_Gen          thrpt   10     0.002 ±   0.002  MB/sec
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.churn.G1_Old_Gen.norm     thrpt   10     0.001 ±   0.001    B/op
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.count                     thrpt   10    88.000            counts
SpanBenchmark.simpleSpanStartAddEventEnd_10Threads:·gc.time                      thrpt   10    73.000                ms
```

### CODE REVIEW

**Comment by jkwatson** [comment]
The specification you reference also includes testing the export pipeline through the OTLP exporter, which isn't included in this benchmark (intentionally). What are your thoughts about testing the full scenario that is described by the spec?

I'm not opposed to changing this benchmark code (although now any older benchmarks become irrelevant, because the scenario has changed), but I wouldn't want to say that the performance testing described in that spec is complete, unfortunately.

**Comment by srprash** [comment]
Yes. I'm working on adding the benchmark with the OTLP exporter in the [SpanPipelineBenchmark](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java). I'll add that here in subsequent commits. That would make the benchmark complete.

**Comment by srprash** [comment]
@jkwatson When you say "although now any older benchmarks become irrelevant, because the scenario has changed", are the older benchmarks published somewhere?

**Comment by jkwatson** [comment]
> @jkwatson When you say "although now any older benchmarks become irrelevant, because the scenario has changed", are the older benchmarks published somewhere?

Hmm. possibly? Maybe on the original PR that submitted them, if anywhere. As I said...it's not a strong objection, just a thought I had.

**Comment by jkwatson** [comment]
> Yes. I'm working on adding the benchmark with the OTLP exporter in the [SpanPipelineBenchmark](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java). I'll add that here in subsequent commits. That would make the benchmark complete.

I'd be happy to get this bit in first, if you'd prefer; I just wanted to make sure we didn't think we were done with just this change. :)

**Comment by srprash** [comment]
> > Yes. I'm working on adding the benchmark with the OTLP exporter in the [SpanPipelineBenchmark](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/all/src/jmh/java/io/opentelemetry/sdk/trace/SpanPipelineBenchmark.java). I'll add that here in subsequent commits. That would make the benchmark complete.
> 
> I'd be happy to get this bit in first, if you'd prefer; I just wanted to make sure we didn't think we were done with just this change. :)

Sure, I'd prefer this to be merged in. And I acknowledge that we need the benchmarks with OTLP exporter as well, which I'll do in a separate PR.

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
