### PR TITLE
OT Shim initial baggage support

### PR DESCRIPTION
**Pull request by carlosalberto**
This is an updated version of the OT initial support, which now maintains the OT SpanContext immutability invariant.

Things to notice:

1) Baggage/tags support for Binary is not done at the moment - I've suspended it till we decide on whether we got for a single payload or use keys + binary values.
2) Needs to adjust the `Tagger` being used by default - will update once `OpenTelemetry` has it.
3) When users use the OT Shim with non-OT Shim code, the Baggage/Tags may be lost, as the user would have to explicitly extract/inject it:

  OT shim --> OT shim - WORKS automatically
  OT shim --> OTel code extracts/inject --> OT shim -- EXPLICIT invocation.

Because of this, I was tempted to use `Tracestate`, but we would be 'wasting' the new Tags component. Not sure this is what we want ;)

@pavolloffay @yurishkuro

### CODE REVIEW

**Comment by yurishkuro** [comment]
> OT shim --> OTel code extracts/inject --> OT shim -- EXPLICIT invocation.

This sounds like it doesn't  meet the stated goals of interop. I realize it's not an easy problem to solve, but without solving it we're still forcing people to do a big-bang upgrade from OT-instrumentation to mix or OTel-only instrumentation.

**Comment by bogdandrutu** [comment]
@carlosalberto can you give a bit more details about this problem? I feel like I did not completely understand some of the comments:

> When users use the OT Shim with non-OT Shim code, the Baggage/Tags may be lost, as the user would have to explicitly extract/inject it:
> OT shim --> OT shim - WORKS automatically
> OT shim --> OTel code extracts/inject --> OT shim -- EXPLICIT invocation.

**Comment by carlosalberto** [comment]
So essentially it works like this:

1. OT Shim injects a SpanContext shim into a carrier:
    * SpanContext is injected
    * Related Baggage (TagMap) is injected as well.
2. OT Shim extracts a carrier:
    * SpanContext is extracted
    * Baggage (TagMap) is **automatically** extracted as well.
    * Both are wrapped by a SpanContext shim.
3. OT Shim injects a SpanContext shim (see step 1).

Now, when using it without a OT Shim on the other side, step 2 and 3 change:

2. OTel extracts a carrier:
    * SpanContext is extracted (**common case**).
    * TagMap has to be extracted **explicitly** (which happened out of the box for the OT Shim).
3. OTel injects a carrier:
    * SpanContext is injected
    * TagMap has to be injected **explicitly**.

I don't know how common is, or will be, for the user to try to extract/inject a `TagMap` alongside the `SpanContext`. If this will be a common pattern (and we make that clear to the OT users when using the OT shim), that will be fine.

Thoughts?

**Comment by pavolloffay** [comment]
> Now, when using it without a OT Shim on the other side, step 2 and 3 change:

Do you mean just OpenTelemetry API? If so I think it's fine, it's a new service and it's expected users will handle the tags/baggage properly with the new API

**Comment by bogdandrutu** [comment]
@carlosalberto what you are saying is that when someone writes an instrumentation with OpenTelemetry they need to make sure they inject/extract both SpanContext and TagMap.

@yurishkuro I think this is not a backwards incompatible change, and the only thing it requires is that when we start migrating the current instrumentation code with OpenTracing to make sure we inject/extract both parts.

**Comment by bogdandrutu** [comment]
@carlosalberto ping on this.

**Comment by carlosalberto** [comment]
Hey @bogdandrutu 

Sorry for the delayed answer - porting the `testbed` cases from OT took me longer than expected ;)

> what you are saying is that when someone writes an instrumentation with OpenTelemetry they need to make sure they inject/extract both SpanContext and TagMap.

Yeah, this is exactly the case.

Btw, I will be putting some iterations on this item this week ;)

**Comment by carlosalberto** [comment]
Closing it in favor of #482

**Pull request closed without merging**
