### PR TITLE
Update bucket hist defaults to match spec

### LINKED ISSUE #4665: Default bucket boundaries for explicit bucket histogram are different from specification
The [java default](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExplicitBucketHistogramUtils.java#L24-L25) explicit bucket histogram bucket boundaries are:

`[5, 10, 25, 50, 75, 100, 250, 500, 750, 1_000, 2_500, 5_000, 7_500, 10_000]`

But according to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation) should be:

`[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 1_000 ]`

### PR DESCRIPTION
**Pull request by breedx-splk**
Resolves #4665

### CODE REVIEW

**Comment by jack-berg** [comment]
I think we need to think this through as it might be a breaking change. In the past, we rejected the idea of a "best available histogram" which would use explicit bucket histogram until the exponential histogram became available. The thinking being that a change like that would be breaking for a user. In that discussion we also talked about how even changes of bucket boundaries would be a breaking change for users if their backends / dashboards depend on them.

I think we should go forward with this change since I think alignment with the spec trumps users becoming dependent on a behavioral bug. Also, the sooner we fix it the better. Still, we should discuss. Maybe there's a graceful way to make this change.

**Comment by breedx-splk** [comment]
> I think we should go forward with this change since I think alignment with the spec trumps users becoming dependent on a behavioral bug. Also, the sooner we fix it the better. Still, we should discuss. Maybe there's a graceful way to make this change.

Yeah, I think one could argue that it's less of a "breaking" change and more of a "fixing" change 🙃 ...but I do respect the sensitivity to changing things out from under users.

But yeah, completely reasonable to sit on this until we can talk about it, probably next week.

**Comment by jkwatson** [comment]
if we do want to do this, we would definitely need to add some very visible language to the change log about it, I think.

**Review by jack-berg — APPROVED** [review]
After more thought, I'm in favor of proceeding with this and including a very clear message in the changelog describing the behavioral change. We can include an example of how to use the file based view configuration to achieve the previous configuration, now that aggregation arguments [can be specified](https://github.com/open-telemetry/opentelemetry-java/pull/4588).

**Review by kubawach — APPROVED** [review]

**Comment by jack-berg** [comment]
Got an implementation ready for #4699 so I'm ready to merge this.

**Review by jkwatson — APPROVED** [review]

**Pull request merged**
