### PR TITLE
Implementation of a Span Exporter that sends data to the New Relic Trace API

### PR DESCRIPTION
**Pull request by jkwatson**
This also adds methods to `SpanId` and `TradeId` to make it easier to make hex ids out of the binary keys in the protobufs.

### CODE REVIEW

**Comment by jkwatson** [comment]
I signed it

**Comment by bogdandrutu** [comment]
Hi @jkwatson in general we will not want to have Vendor specific exporters in the main repo. While we do some testing in the initial phase this is good, but when we get to beta we would like every Vendor to host their own exporters.

**Comment by jkwatson** [comment]
oh! I wasn't aware of that. We can definitely host this ourselves, no problem. Do you want to keep this in here, or would you prefer we close this PR and move this to our own GH org?

**Comment by jkwatson** [comment]
@bogdandrutu so, should we close this PR, and open up one that just has the change we need in `SpanId` and `TraceId` to enable creating hexadecimal string ids?

**Comment by jkwatson** [comment]
closing this for now, pending completion of #557

**Pull request closed without merging**
