### PR TITLE
Move TestSpanData to a testing package instead of in the published SDK.

### PR DESCRIPTION
**Pull request by anuraaga**
Extracted this out of #1502

### CODE REVIEW

**Comment by huntc** [comment]
Any thoughts on how authors of exporters external to this project can now create test span data?

**Comment by anuraaga** [comment]
That's a good callout - I think in addition to `TestSpanData`, there are many potential utilities we could provide (assertj assertion class for `Span`?). @jkwatson any thoughts on publishing an `opentelemetry-testing` artifact?

**Comment by huntc** [comment]
> That's a good callout - I think in addition to `TestSpanData`, there are many potential utilities we could provide (assertj assertion class for `Span`?). @jkwatson any thoughts on publishing an `opentelemetry-testing` artifact?

Yeah... like a test kit in general...

**Comment by jkwatson** [comment]
I think publishing an opentelemetry-testing artifact would be great. I'll create an issue for it.

**Comment by jkwatson** [comment]
https://github.com/open-telemetry/opentelemetry-java/issues/1647

**Pull request merged**
