### PR TITLE
Remove Binary format and related members.

### PR DESCRIPTION
**Pull request by carlosalberto**
As part of 0.3.0 we will be removing `Binary` (and later, under 0.5.0, putting it back once the format gets updated).

This is part of #720

### CODE REVIEW

**Comment by Oberon00** [comment]
Would it be easier to leave BinaryContext in a non-working form here? If we temporarily remove it, we break users now and later they have to put it back. If we don't remove it, we break them later and they can change their usage to the new interface right away.

**Comment by carlosalberto** [comment]
I'm not sure we will be breaking users, because I don't think anybody has been using this (for example, we don't have binary support for `CorrelationContext` and the one for tracing is rather experimental).

In JS they decided to keep it because there were pieces already using it, so it makes sense for them to keep things around, but that's not our case. I can keep them around, but it feels weird to me to keep around 'dead-for-now' code ;)

**Comment by Oberon00** [comment]
We plan to use the BinaryFormat interface at Dynatrace, with our own implementation. But if you think no one else is using it, we don't really require having that interface in the API.

**Comment by carlosalberto** [comment]
I don't think anybody else than you guys is using it at this time. I imagine users relying on that once we have a full implementation though (not a partial one like the one we have right now).

I'm adding then the "Holding On" label, in case we don't move fast enough on the OTEP 66 changes ;)

**Comment by carlosalberto** [comment]
Ooops, was expected to put the label to #914 

@bogdandrutu Please provide your review/opinion on this one ;)

**Comment by bogdandrutu** [comment]
Please rebase, also I am not sure what was the decision.

**Comment by carlosalberto** [comment]
Rebased and updated. The decision from the last SIG call was to temporary remove it.

@open-telemetry/java-approvers please review & approve.

**Pull request merged**
