### PR TITLE
Fix typo in exception message

### PR DESCRIPTION
**Pull request by keithc-ca**
Should be 'plain' instead of 'plan' which matches nearby comment.

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]

**Comment by jkwatson** [comment]
@keithc-ca Can you sign the CLA so we can get this merged? Thanks!

**Comment by keithc-ca** [comment]
> Can you sign the CLA so we can get this merged?

I am awaiting approval from my employer to do so.

**Comment by keithc-ca** [comment]
I believe I should have authorization now. Does the check need to be re-run?

**Comment by keithc-ca** [comment]
It seems I had to do the 'EasyCLA' step again. It appears to have reported success here.

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Thanks @keithc-ca!

**Pull request merged**
