### PR TITLE
Add @theletterf as docs codeowner

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
cc @theletterf

### CODE REVIEW

**Comment by jack-berg** [comment]
I saw [this related issue](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1275) in dotnet, but I'm not sure I understand. What's @theletterf's role such that they should be notified about changes to docs?

**Comment by mateuszrzeszutek** [comment]
Fabri is a tech writer in Splunk, he wanted to support us with whatever docs-related work we have

**Comment by jkwatson** [comment]
I think before we add @theletterf as a codeowner, I'd like to see some contributions/maintenance to the docs here.

**Comment by theletterf** [comment]
Fine by me! The mention system also worked fine in the past; I guess the purpose of the PR is to push more docs stuff in front of my eyes.

What’s a good starting point?

**Comment by jack-berg** [comment]
> What’s a good starting point?

We don't have a backlog of doc related issues. From my perspective, the docs in this repo are in good shape. If anything needs help, its the java docs in [opentelemetry.io](https://opentelemetry.io/docs/instrumentation/java/getting-started/). I don't have a specific list of things that need work, but my general read is that the docs could cover more material and benefit from some improved organization.

**Pull request closed without merging**
