### PR TITLE
Iterations benchmark

### PR DESCRIPTION
**Pull request by DotSpy**
Should solve https://github.com/open-telemetry/opentelemetry-java/issues/933

### CODE REVIEW

**Comment by jkwatson** [comment]
can you add images of the benchmark output to the PR description? Maybe before & after would be nice, as well.

**Comment by jkwatson** [comment]
also, looks like checkstyle failed on this change

**Comment by bogdandrutu** [comment]
Closed and re-opened to force CLA recheck :)

**Comment by DotSpy** [comment]
Old:
image
New:
image
P.S. @bogdandrutu starting ti think that u are hating me :)

**Comment by jkwatson** [comment]
Thanks for the images. Can you explain how this new version is more readable than the old? It looks exactly the same to my untrained eyes. Or, is there something else in the output that #933 is referring to?

**Comment by DotSpy** [comment]
@jkwatson there was a huge discussion about it https://github.com/open-telemetry/opentelemetry-java/pull/905 u can read comments here + i moved out from benchmark all thing but method call

**Comment by jkwatson** [comment]
Cool. Interesting that the screenshots seem to suggest *less* precision in the new version, with a much larger error bar. Of course, without stable hardware, this all might be red herrings. :)

**Comment by DotSpy** [comment]
@jkwatson maybe u have some books\videos about jmh?

**Comment by jkwatson** [comment]
> @jkwatson maybe u have some books\videos about jmh?

I am very far from being a jmh expert. This project is the first time I've ever written jmh benchmarks. :)

**Pull request merged**
