### PR TITLE
Add compressor SPI to support additional compression algos

### PR DESCRIPTION
**Pull request by jack-berg**
Related to #5196.

I would say this closes the issue, but we might also consider adding a contrib artifact containing one or more popular alternatives to gzip. 

If folks agree on the direction, I'll followup on this to extend support to the gRPC version of the OTLP exporters.

### CODE REVIEW

**Comment by jack-berg** [comment]
Draft PR to add a zstd implementation to contrib: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1108

**Comment by jkwatson** [comment]
I think this seems like a great approach.  One very small comment: it might be better not to pull in another test dependency, but just create a fake compressor (maybe one that just base64s or something if you want it to change the payload) for testing.  Only better in that it's one less dependency that has to be maintained/upgraded/etc.

**Comment by jack-berg** [comment]
Nice suggestion. I pushed a commit to use base64 to test the mechanism and removed the lz4 dependency.

**Review by jkwatson — APPROVED** [review]
👍🏽

**Pull request merged**
