### PR TITLE
Document precedence order is multiple context propagators are used

### LINKED ISSUE #1271: Document precedence order is multiple context propagators are used
```java
    ContextPropagators contextPropagators = DefaultContextPropagators.builder()
        .addHttpTextFormat(new JaegerPropagator())
        .addHttpTextFormat(new HttpTraceContext())
        .build();
    OpenTelemetry.setPropagators(contextPropagators);
```

The `DefaultContextPropagators.Builder` should document precedence order when multiple context propagation formats are used - especially for extraction.  At the moment all formats are extracted and the last one is returned.

https://github.com/open-telemetry/opentelemetry-java/blob/690651b65a938c903c35d65aef3182999fcb1b19/context_prop/src/main/java/io/opentelemetry/context/propagation/DefaultContextPropagators.java#L72

### PR DESCRIPTION
**Pull request by malafeev**
fix #1271

### CODE REVIEW

**Comment by Oberon00** [comment]
I think this is currently unspecified in the spec, as https://github.com/open-telemetry/opentelemetry-specification/issues/496 is still open. If so, I think we should leave this unspecified in Java too to be able to follow the spec later without breaking documented behavior.

**Comment by jkwatson** [comment]
> I think this is currently unspecified in the spec, as [open-telemetry/opentelemetry-specification#496](https://github.com/open-telemetry/opentelemetry-specification/issues/496) is still open. If so, I think we should leave this unspecified in Java too to be able to follow the spec later without breaking documented behavior.

ping @malafeev

**Comment by carlosalberto** [comment]
I'm tempted to state/document here that the order is undefined for the time being. That way at least we are not tied for now ;) Does that sound right? If YES, @malafeev, you can iterate on this PR ;)

**Comment by malafeev** [comment]
updated

**Review by jkwatson — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
