### PR TITLE
Use LinkedList for better performance

### PR DESCRIPTION
**Pull request by reugn**

### CODE REVIEW

**Comment by anuraaga** [comment]
We don't except non-append operations to be common in practice so I'm not sure this change would improve performance in practice. We'll need JMH numbers to consider this change.

**Comment by anuraaga** [comment]
Oops, realized that even append is adding to the front. We could probably either reverse the list, provide a reversed list view, or some other approach not requiring the allocation overhead of a linkedlist

**Comment by reugn** [comment]
@anuraaga it's an internal tweak, the returned object on build is an ArrayList.

**Comment by anuraaga** [comment]
Ah in that case even more so, we need to compare the JMH numbers. For example compared to reversing an ArrayList

**Comment by knutwannheden** [comment]
I think an ArrayDeque would be the appropriate data structure to use here. I could provide an alternate PR.

**Comment by jkwatson** [comment]
> I think an ArrayDeque would be the appropriate data structure to use here. I could provide an alternate PR.

Any internal implementation changes like this will need to be accompanied by benchmarks that clearly show a performance improvement.

**Comment by anuraaga** [comment]
@reugn This was superceded by #4325. A benchmark was added there too so if you see anything left to try it will be easier to accept. Thanks

**Pull request closed without merging**
