### PR TITLE
Fix OpenTracingShim to run with SDK without baggages.

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/605

### CODE REVIEW

**Comment by jkwatson** [comment]
So, this will let it work without blowing up. I assume we'll still end up with broken traces at this point (which is better than a dead span, for sure).

**Comment by bogdandrutu** [comment]
It is not broken trace (the distributed context in opentelemetry is equivalent with opentracing baggage) so you will have correct traces but no support for baggages.

**Comment by jkwatson** [comment]
Interesting. I'm clearly fuzzy on some of the internal details of how this will work. Let's :shipit: and I'll give it a try!

**Comment by jkwatson** [comment]
I tested this fix locally and it works great.

**Pull request merged**
