### PR TITLE
AutoConfiguredOpenTelemetrySdkBuilder does not set GlobalOpenTelemetry by default

### PR DESCRIPTION
**Pull request by jack-berg**
GlobalOpenTelemetry makes you opt into initializing with autoconfigure by setting a environment variable / system property.

In contrast, AutoConfiguredOpenTelemetrySdk will set GlobalOpenTelemetry by default. This PR aligns AutoConfiguredOpenTelemetrySdk with the opt-in behavior of GlobalOpenTelemetry, and also with our general advice discouraging use of GlobalOpenTelemetry.

Also, this PR changes AutoConfiguredOpenTelemetrySdkBuilder#setResultAsGlobal(boolean) to simply be AutoConfiguredOpenTelemetrySdkBuilder#setResultAsGlobal(). This means there is no option to undo a decision to `setResultAsGlobal` after its previously been invoked. 

This aligns with our builders elsewhere.

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
👍🏽

**Comment by gabrieljones** [comment]
@jack-berg 
https://opentelemetry.io/docs/concepts/instrumentation/libraries/#getting-a-tracer
This does the opposite of `discouraging use of GlobalOpenTelemetry`.

**Comment by jack-berg** [comment]
Yikes @gabrieljones. I'll open an issue / PR to fix that.

**Comment by jack-berg** [comment]
See issue https://github.com/open-telemetry/opentelemetry.io/issues/3692.

**Comment by gabrieljones** [comment]
Hmmm, the

> AutoConfiguredOpenTelemetrySdk found on classpath but automatic configuration is disabled.

 warning also seems to "encourage" the use of `GlobalOpenTelemetry`.

Attempting to resolve this warning led me into a head on collision with the advice not to use GlobalOpenTelemetry.

Is there a way to suppress this warning so that the users of my app are not spooked.

Right now I do:
```scala
    val openTelemetry: OpenTelemetry = AutoConfiguredOpenTelemetrySdk.builder.build().getOpenTelemetrySdk
```

Is there a more correct way to retrieve a non Global instance of `OpenTelemetry` from `AutoConfiguredOpenTelemetrySdk` so that the warning is not triggered?

**Comment by jack-berg** [comment]
> Oh I see, the warning is triggered because something somewhere is calling GlobalOpentelemetry.get()
> If I get rid of all of those then the warning should go away.

Yup - maybe we should log something more clear / actionable 🤔

**Pull request merged**
