### PR TITLE
Ignore invalid usage of TraceState instead of throwing.

### PR DESCRIPTION
**Pull request by anuraaga**
Similar to #1964 and because of https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
Thanks!

**Comment by Oberon00** [comment]
I don't like how we completely ignore that, and not even log anything. That might lead to difficult to debug problems. I guess it's better than always throwing though.

**Comment by jkwatson** [comment]
> I don't like how we completely ignore that, and not even log anything. That might lead to difficult to debug problems. I guess it's better than always throwing though.

I'd be ok with logging at FINE or FINEST, but I'd hate to introduce a logging-based DOS attack vector via someone sending bad trace state headers.

**Comment by Oberon00** [comment]
Yes, I agree this is something that should not be logged by default.

**Comment by anuraaga** [comment]
I think we need to do the same for many different parameters we don't validate, baggage, span, etc. I don't think it's a simple as adding `Logger` into each class, it's better to have a central class for logging validation messages I think - it will make it easier for users to replace them with exceptions or raise their level by themselves, etc. So can we do it separately in a consistent way?

**Comment by jkwatson** [comment]
> I think we need to do the same for many different parameters we don't validate, baggage, span, etc. I don't think it's a simple as adding `Logger` into each class, it's better to have a central class for logging validation messages I think - it will make it easier for users to replace them with exceptions or raise their level by themselves, etc. So can we do it separately in a consistent way?

Having one named logger for validation messages seems like a good idea. And, yes, it definitely doesn't need to be in this PR.

**Comment by jkwatson** [comment]
Logged #2093 to track the logging of API mis-use.

**Pull request merged**
