### PR TITLE
Stop publishing jaeger protos

### PR DESCRIPTION
**Pull request by jack-berg**
Related to #4482.

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]

**Comment by anuraaga** [comment]
Oh missed Jaeger on the original issue. The only reason we publish them is we had published them as non-alpha mistakenly already. It's not semver compliant to stop publishing them I think. It's fine to stop documenting them though.

**Comment by jkwatson** [comment]
> Oh missed Jaeger on the original issue. The only reason we publish them is we had published them as non-alpha mistakenly already. It's not semver compliant to stop publishing them I think. It's fine to stop documenting them though.

One could argue if you never change an artifact, it will never have any breaking changes!

**Comment by anuraaga** [comment]
It would mean one artifact that people may be using happens to not be managed by the BOM though looking very similar to our others. I feel the cost of publishing an artifact is not high enough to create this inconsistency if it's just removed from documentation.

**Comment by anuraaga** [comment]
I think there is also some mindset / philosophy - if we publish Java code as stable, we commit do continuing to publish it until a next major version. I guess we don't document this particular case in VERSIONING, but doing that just seems to be more robust in terms of promising semver.

**Comment by jkwatson** [comment]
I agree that the cost of this artifact is quite low to us, and I suspect it will never end up actually needing any maintenance. We should put a disclaimer in the docs that it will not have any changes in the future, but will continue to be published as-is.

**Pull request closed without merging**
