### PR TITLE
Include only prod artifacts in BOM.

### PR DESCRIPTION
**Pull request by anuraaga**

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
👍 you beat me to it!

**Comment by Oberon00** [comment]
I don't understand the reason for this. The alpha artifacts should be aligned with the corresponding release versions & dependency versions too, shouldn't they? Removing them from the BOM makes them harder to use, but does it bring any advantages for maintainability?

**Comment by anuraaga** [comment]
@Oberon00 We're thinking of providing an `-alpha-bom` artifact with them. We want to make sure a user has the word `alpha` somewhere in their build file so they know they are opting into to something that will likely break them.

**Comment by Oberon00** [comment]
Understood. That makes sense.

**Pull request merged**
