### PR TITLE
Improve key validity code documentation for trace state

### PR DESCRIPTION
**Pull request by jamesylgan**
- [x] Switch from multiple single line comments to multi-line javadoc format
- [x] Add documentation onto the public method so that users will know how to construct valid keys 
- [x] Addressed code style issues raised by CI

### CODE REVIEW

**Comment by jkwatson** [comment]
Thanks for this doc cleanup! Looks like it still needs some tweaking to get checkstyle to agree.

**Comment by jamesylgan** [comment]
> Thanks for this doc cleanup! Looks like it still needs some tweaking to get checkstyle to agree.

Whoops :)

**Comment by jamesylgan** [comment]
@jkwatson any way the CI checks could be changed to include `actual` as well as `expected`? If this is an external CI tool, then nevermind, but if it's changeable, would help here

`[Task :api:all:checkstyleMain FAILED] [JavadocTagContinuationIndentation] Line continuation have incorrect indentation level, expected level should be 4.`

**Comment by jkwatson** [comment]
> @jkwatson any way the CI checks could be changed to include `actual` as well as `expected`? If this is an external CI tool, then nevermind, but if it's changeable, would help here - it seems to complain with 4 spaces before the asterisk, so not entirely sure what it is looking for
> 
> `[Task :api:all:checkstyleMain FAILED] [JavadocTagContinuationIndentation] Line continuation have incorrect indentation level, expected level should be 4.`

Have you run `./gradlew spotlessApply` ? That should reformat the javadoc to the expected format. I don't think we have any power to change how checkstyle/spotless formats its errors.

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
