### PR TITLE
Updated Sampling Result names

### PR DESCRIPTION
**Pull request by eunice98k**
This PR updates the names of Sampling result for consistency, closing [#1648](https://github.com/open-telemetry/opentelemetry-java/issues/1648)

The changes have been made following these specifications:  
[open-telemetry/opentelemetry-specification#938](https://github.com/open-telemetry/opentelemetry-specification/pull/938)
[open-telemetry/opentelemetry-specification#956 ](https://github.com/open-telemetry/opentelemetry-specification/pull/956)

Changed from:

- `NOT_RECORD`

- `RECORD`

- `RECORD_AND_SAMPLED`

Changed to: 

- `DROP`

- `RECORD_ONLY`

- `RECORD_AND_SAMPLE`

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
Looks great. Let's hold off on merging until the DROP spec PR is merged. Thanks!

**Review by anuraaga — COMMENTED** [review]
Thanks @eunice98k - can you run `./gradlew googleJavaFormat` to fix the formatting violations!

**Review by thisthat — APPROVED** [review]
Thank you for your contribution :)

**Review by arminru — APPROVED** [review]

**Comment by Oberon00** [comment]
@thisthat No need to add blocked:spec, open-telemetry/opentelemetry-specification#956 is merged already.

**Comment by thisthat** [comment]
> @thisthat No need to add blocked:spec, [open-telemetry/opentelemetry-specification#956](https://github.com/open-telemetry/opentelemetry-specification/pull/956) is merged already.

oh yeah! My bad! I blindly read the comment of @jkwatson and add the label without a double check!

**Comment by jkwatson** [comment]
@eunice98k looks like this needs a rebase, and a run of the formatter, then should be good to go. Thanks!

**Comment by jkwatson** [comment]
It looks like this PR now includes commits from previously merged PRs. I think those need to be removed from this PR.

**Pull request closed without merging**
