### PR TITLE
Fix SDK Config documentation

### PR DESCRIPTION
**Pull request by jack-berg**
Several of the example snippets in the SDK configuration documentation were outdated. I went ahead and updated them.

There are several other chunks of text that are no longer accurate, but I held off on fixing them because they discuss philosophies and future direction which I'm not familiar enough with to represent. But it'd be great if someone could do a read through and update the text as well.

### CODE REVIEW

**Comment by jkwatson** [comment]
This particular document was/is a design document, and not a how-to or precise documentation. I don't think we had intended on keeping it up to date when we actually implemented the design. I'm not opposed to keeping it up to date, but it wasn't the purpose. :)

**Comment by jack-berg** [comment]
Gotcha. Shall I close this then?

**Comment by jkwatson** [comment]
up to you. If you think there's value in keeping it up to date, I'll give it a once-over and merge it.

**Comment by jack-berg** [comment]
I just remember stumbling upon it a while back and copying one of the snippets, and having to figure out how to update all the stuff to get it to work. I don't think it hurts to have the code snippets up to date.

**Comment by jkwatson** [comment]
cool. Could you also put a big disclaimer at the top about it being a design doc, and point at our QUICKSTART (or skip the redirect and point directly at the public website docs?)

**Comment by jack-berg** [comment]
Great yeah I like that idea.

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
