### PR TITLE
Move obfuscated to sdk, make it package protected

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
there's an open PR to remove this altogether. #2202 . If we don't remove it, then hiding it is good.

**Comment by bogdandrutu** [comment]
I would do the hiding first since it unblocks my work of reducing the internal package (or even removing if possible).

**Comment by bogdandrutu** [comment]
@jkwatson this should be uncontroversial, the removing still has open questions.

**Comment by jkwatson** [comment]
@trask @anuraaga does this have any impact on the agent (I suspect not, but thought I'd give a heads-up in case this is a terrible change)?

**Review by jkwatson — APPROVED** [review]
👍

**Comment by bogdandrutu** [comment]
@jkwatson do you suggest to wait for this then? Maybe at least @trask can confirm :)

**Comment by jkwatson** [comment]
> @jkwatson do you suggest to wait for this then? Maybe at least @trask can confirm :)

we can revert if need-be. Just wanted to raise awareness.

**Pull request merged**
