### PR TITLE
Remove unused package-info from context_prop io.otel.context

### PR DESCRIPTION
**Pull request by MariusVolkhart**
The presence of package-info.java in the io.opentelemetry.context package of the io.opentelemetry.context.propagation JPMS module results in a split package, due to the io.opentelemetry.context module declaring the same package. This causes big problems for JPMS consumers.

Since the package-info.java is unused, removing it should not cause any problems.

### CODE REVIEW

**Comment by anuraaga** [comment]
I thought JPMS is concerned with package boundaries, not "package prefix" - aren't `.context` and `.context.propagation` different packages? Just want to ask since I am not that familiar with it TBH.

This package-info is mostly for the `@ParametersNonNullByDefault` annotation which I think is important. I think context_prop artifact can / should be merged (in-process and remote context propagation are basically same concept) into context and have been thinking of doing it but will definitely do it sooner if the split is causing some breakage. @jkwatson what do you think?

**Comment by anuraaga** [comment]
Oh doh! Now I get it :)

**Review by anuraaga — APPROVED** [review]
Thanks!

**Review by jkwatson — APPROVED** [review]
good catch!

**Pull request merged**
