### PR TITLE
Rename OpenTelemetry interface methods to normal interface conventions.

### PR DESCRIPTION
**Pull request by anuraaga**
This includes #1805 currently

### CODE REVIEW

**Comment by Oberon00** [comment]
> This includes #1805 currently

https://github.com/anuraaga/opentelemetry-java/compare/opentelemetry-interface...anuraaga:rename-interface-methods

Should be a more useful diff then (though there is a merge conflict according to GH)

**Comment by jkwatson** [comment]
with #1805 merged, looks like this is ready for a rebase. Thanks!

**Comment by anuraaga** [comment]
Based!

**Review by jkwatson — APPROVED** [review]
Lookin' good

**Pull request merged**
