### PR TITLE
Remove unnecessary setPropagators from OpenTelemetry interface

### PR DESCRIPTION
**Pull request by bogdandrutu**
Example usage in the `Application.java`.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by jkwatson — CHANGES_REQUESTED** [review]
I think we need to put a temporary hold on any changes to the SDK configuration code. We need someone to create a design document that shows the end state, so we can make sure we're all pulling in the same direction and going where we all agree we're trying to go.

**Comment by bogdandrutu** [comment]
@jkwatson this is not about SDK configuration, this is an API change. And I don't think we should require all API implementations to support set propagators.

**Comment by jkwatson** [comment]
Sorry, yes, this isn't SDK configuration code, it's API configuration code. I'm definitely not opposed to this change, but it is definitely a breaking change to the API, so we should deprecate for at least one release before removing it. 

Just to be clear: I think this is a good reduction in surface, but I need to see a full story around API & SDK configuration to understand where we're going and where we think we're going to end up with how to configure this thing.

**Comment by jkwatson** [comment]
ok! I think this is a good change, moving toward only setting propagators at implementation creation time. 
But, we should definitely deprecate before removing.

And, this needs a rebase. :)

Thanks!

**Review by carlosalberto — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
