### PR TITLE
Update proto to latest proto commit

### PR DESCRIPTION
**Pull request by bogdandrutu**
Related to https://github.com/open-telemetry/opentelemetry-java/issues/2021 

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by jkwatson** [comment]
Wait! Is this a released version of the proto?

**Review by jkwatson — CHANGES_REQUESTED** [review]
We should not use a non-released version of the proto

**Comment by bogdandrutu** [comment]
@jkwatson do we?

**Comment by jkwatson** [comment]
> @jkwatson do we?

I assert yes, we should only use released versions of the protobuf.

**Comment by gcacace** [comment]
Can we please then do a release of proto and then another one for the java package?

**Comment by jkwatson** [comment]
> Can we please then do a release of proto and then another one for the java package?

Can you explain why this is needed so urgently? We are on a 2 week release cycle now, and do not generally intend to release patch releases unless there is an urgent bugfix.

**Comment by gcacace** [comment]
Because we need the new `DoubleSummary` data structure as per https://github.com/open-telemetry/opentelemetry-specification/issues/1146 and https://github.com/open-telemetry/opentelemetry-specification/issues/1145

**Comment by jkwatson** [comment]
> Because we need the new `DoubleSummary` data structure as per [open-telemetry/opentelemetry-specification#1146](https://github.com/open-telemetry/opentelemetry-specification/issues/1146) and [open-telemetry/opentelemetry-specification#1145](https://github.com/open-telemetry/opentelemetry-specification/issues/1145)

What explains what you need, but not why it is so urgent that we would be forced to do a patch release.

**Comment by jkwatson** [comment]
Also, just updating the protobuf won't mean that we're actually using the protobuf structures for anything. How is just updating the protobuf definitions going to help you at all?

**Comment by gcacace** [comment]
Because we are using opentelemetry-proto as transport layer for our use case.

**Comment by jkwatson** [comment]
> Because we are using opentelemetry-proto as transport layer for our use case.

So...let me understand. You're using the java repo's published generated protobuf classes for something other than use in the SDK? That does not sound like a reason for us to do an emergency patch release. If you need these protobuf classes for something outside the use in the SDK, I recommend setting up a project that will build and publish those for you, rather than depending on this project with just happens to publish them as a part of the release process.

**Comment by jkwatson** [comment]
IMO, the correct solution to this problem is to have the protobuf repository publish various language bindings. Then, the opentelemetry-java project could depend on them like a normal library (rather than as a git submodule), and usages by other projects would be supported as well.

**Comment by gcacace** [comment]
> IMO, the correct solution to this problem is to have the protobuf repository publish various language bindings. Then, the opentelemetry-java project could depend on them like a normal library (rather than as a git submodule), and usages by other projects would be supported as well.

Agree, since for our use case we only need the OT Protobuf per-language bindings.

**Comment by anuraaga** [comment]
I agree that publishing stubs from the opentelemetry-proto repo would be ideal for contributor experience and version management.

I have sent https://github.com/open-telemetry/opentelemetry-proto/pull/231 as a proposal to start to make that happen.

For reference, I've done something similar on a previous project and it works pretty well https://github.com/infostellarinc/stellarstation-api

**Comment by gcacace** [comment]
Would it be possible to create a new release of the proto with `DoubleSummary` support?

**Comment by jkwatson** [comment]
> Would it be possible to create a new release of the proto with `DoubleSummary` support?

Please post that question in the proto repo, since it's not something the java folks control.

**Comment by jkwatson** [comment]
closing this. when the proto project cuts a release, I'll be happy to update our dependency.

**Pull request closed without merging**
