### PR TITLE
Remove unused class InMemoryTracing, junit5 helper is enough

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by anuraaga** [comment]
I think we should add a junit4 rule (and switch current junit5 dependency to compileOnly) before removing this, I can get on it.

**Review by jkwatson — APPROVED** [review]
Thanks! Cleanup FTW

**Review by carlosalberto — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@anuraaga is it ok if we merge this and you provide later the extension?

**Comment by anuraaga** [comment]
I'm hoping we don't make a release with no junit4 support. Will be working on that today, if it seems likely to merge into a release then I have no problem with merging this in advance.

**Comment by anuraaga** [comment]
Sent #1996

**Pull request merged**
