### PR TITLE
Use the concise license header without the year

### PR DESCRIPTION
**Pull request by dengliming**
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1212](https://github.com/open-telemetry/opentelemetry-java/issues/1212)

### CODE REVIEW

**Comment by jkwatson** [comment]
@bogdandrutu or @carlosalberto is this an acceptable license header? I think it's great, but I don't want to have to revert this if it's not ok with the TC. :)

**Review by jkwatson — APPROVED** [review]
I like it, pending approval from the TC.

**Review by anuraaga — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@jkwatson I saw in other repos using the header without the year  but the license text was still there.

See https://github.com/open-telemetry/community/issues/113#issuecomment-595377568

**Comment by carlosalberto** [comment]
Although Yuri also [states](https://github.com/open-telemetry/community/issues/113#issuecomment-624756075) the two lines license as a valid option, most OTel Projects use the format @bogdandrutu mentioned.

(Maybe it's a good time to finally settle the related discussion in Community)

**Comment by jkwatson** [comment]
If we can get sign-off on this being the preferred header, it's definitely the most concise and light-weight.

**Comment by bogdandrutu** [comment]
@jkwatson pushing on that issue to be closed https://github.com/open-telemetry/community/issues/113#issuecomment-691227617

**Comment by anuraaga** [comment]
@dengliming Sorry for the delay on this! I see the community repo was updated with guidance that allows the short header. Would you be able to merge master and reapply this change? Thanks a lot for the patience.

**Comment by dengliming** [comment]
@anuraaga Thanks. reapply now.

**Comment by anuraaga** [comment]
Thanks so much!

**Pull request merged**
