### PR TITLE
add shortcut methods to get tracers and meters

### LINKED ISSUE #1091: Add shortcut factory method for tracer and meter
inspired by the brevity of [LoggerFactory.getLogger](http://www.slf4j.org/apidocs/org/slf4j/LoggerFactory.html#getLogger(java.lang.String)), I'm proposing to add the same for tracer and meter. Once OpenTelemetry is ready, I'd also suggest to add `LoggerFactory`.

```java
public class TracerFactory {
  public static Tracer get(String instrumentationName) {
    return OpenTelemetry.getTracerProvider().get(instrumentationName);
  }
}

public final class TracerSdk implements Tracer {
  public static TracerSdk get(String instrumentationName) {
    return OpenTelemetrySdk.getTracerProvider().get(instrumentationName);
  }
}
```

Same for meter, with `MeterFactory` and static method in `MeterSdk` - and also the flavor that takes `(String instrumentationName, String instrumentationVersion)` as arguments for both.

### PR DESCRIPTION
**Pull request by zeitlinger**
Fixes #1091.

### CODE REVIEW

**Comment by zeitlinger** [comment]
can someone help me understand the build failure?

**Comment by thisthat** [comment]
It looks like it is a CI problem. Try to push a dummy commit or wait for someone with the powers to retrigger the build :)

**Comment by carlosalberto** [comment]
@zeitlinger Thanks for cooking this PR!

I'd like to have the new methods a note on the fact they are shortcuts (e.g. to `getTracerProvider()`), so users don't get confused on why there are so many methods ;)

**Comment by zeitlinger** [comment]
> In addition to the note that @carlosalberto mentioned, you might want to mention your newly created API in the quickstart guide and sample code as an alternative to the explicit call via tracer/meter provider.

thanks - IDEA didn't find that.
I'll actually make the shortcut method the default.

**Comment by carlosalberto** [comment]
> The change in the quickstart makes it look like this is the primary option for accessing Tracers and Meters. Is that the change we want?

So I *feel* we should use the 'full' path as the default, and offer the shortcuts for further convenience only. No strong opinion though.

**Comment by trask** [comment]
What's the point of the long form? Is there a reason users would ever need to call `OpenTelemetry.getTracerProvider()`? If we can remove the long form, that is very helpful for auto-instrumentation, and eliminates the need for #1152.

**Comment by zeitlinger** [comment]
> What's the point of the long form? Is there a reason users would ever need to call `OpenTelemetry.getTracerProvider()`? If we can remove the long form, that is very helpful for auto-instrumentation, and eliminates the need for #1152.

I agree. If you're OK, I'll remove the long form completely - and also revert the changes in #1152.

**Comment by jkwatson** [comment]
> > What's the point of the long form? Is there a reason users would ever need to call `OpenTelemetry.getTracerProvider()`? If we can remove the long form, that is very helpful for auto-instrumentation, and eliminates the need for #1152.
> 
> I agree. If you're OK, I'll remove the long form completely - and also revert the changes in #1152.

In the SIG meeting last week, we agreed that we need to keep the long form for now, for spec compliance.

**Pull request merged**
