### PR TITLE
Make the ZipkinSpanExporter public, so it can actually be used.

### LINKED ISSUE #1182: Make ZipkinSpanExporter class public
Could you please provide info how to use non public class `ZipkinSpanExporter`?
Is it internal class not for usage by apps?

### PR DESCRIPTION
**Pull request by jkwatson**
resolves #1182

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Probably we should do a patch release?

**Comment by bogdandrutu** [comment]
Or a new release entirely.

**Comment by jkwatson** [comment]
> Or a new release entirely.

probably. It would also be good to pick up the MetricExporterFactory as well, so we can get auto-instrumentation support for metric exporters.

**Comment by bogdandrutu** [comment]
Sure let's then update the release notes and set a deadline for next week

**Pull request merged**
