### PR TITLE
Move results to benchmark folder

### PR DESCRIPTION
**Pull request by tylerbenson**
For consistency with other repos.

Depends on #5874

### CODE REVIEW

**Review by trask — COMMENTED** [review]
do you think the redirect is needed?

**Comment by tylerbenson** [comment]
(I dropped the extra commit where I added the redirect.)

**Review by breedx-splk — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]

**Comment by jack-berg** [comment]
Will merge once the conflict is resolved

**Comment by tylerbenson** [comment]
Done.  Please merge this before merging anything else otherwise another rebase will be required.

**Pull request merged**
