### PR TITLE
feat: make invalid span context public

### PR DESCRIPTION
**Pull request by DotSpy**
Solves https://github.com/open-telemetry/opentelemetry-java/issues/787

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please run `./gradlew goJF`

**Comment by carlosalberto** [comment]
I like this one but I still have mixed feelings. I.e. I'm afraid users will start doing a check like this:

```java
if (spanContext == SpanContext.getInvalid())
```

Instead of

```java
if (!spanContext.isValid())
```

So I'd advise on filling an issue to follow up this PR to review the docs and make sure we discourage users to do that ;)

**Comment by bogdandrutu** [comment]
@carlosalberto are you ok to merge this now?

**Comment by carlosalberto** [comment]
Sure, lets go.

**Pull request merged**
