### PR TITLE
Make the MinMaxSumCount aggregations be true delta aggregations

### PR DESCRIPTION
**Pull request by jkwatson**
This is a follow-on from #1032 to make the MinMaxSumCount aggregations actually create deltas properly, with the timestamps set appropriately.

It also demonstrates the beginnings of how we might make the aggregations be able to behave in a delta or a cumulative mode.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@jkwatson any plan to continue on this or drop?

**Comment by jkwatson** [comment]
Let's close this for now. We can rework this when @jmacd 's work on clarifying how all this should happen is done.

**Comment by jmacd** [comment]
It's a two-part change at this point:
https://github.com/open-telemetry/opentelemetry-go/pull/835
and
in that PR a reference to the remaining work, which is pending on a branch. It's almost finished. :)

**Comment by jmacd** [comment]
FWIW, https://github.com/open-telemetry/opentelemetry-go/pull/840 is the progress I was speaking of.

**Pull request closed without merging**
