### PR TITLE
Convert the ValueObserver instruments to use the LastValue aggegration.

### LINKED ISSUE #1780: Update ValueObserver to have LastValue as default aggregation
ValueObserver should have LastValue as the default aggregation.

### PR DESCRIPTION
**Pull request by jkwatson**
See this spec update:  https://github.com/open-telemetry/opentelemetry-specification/pull/984

Resolves #1780

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]
As mentioned in the Java maintainers meeting. This is partially fixing the issue because our current MetricData does not reflect the latest changes in OTLP and we should produce Gauge for this. Do we want to go ahead with this? That means we will have another breaking change soon when Gauge will be the correct result.

**Comment by jkwatson** [comment]
I think this is the right change for the current released version of OTLP, yes? I think it's fine to address the OTLP changes as a separate issue, once it gets released.

**Comment by bogdandrutu** [comment]
@jkwatson not really, https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java#L117

This will be exported as non-monotonic updown sum I believe which is wrong.

**Comment by jkwatson** [comment]
> @jkwatson not really, https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java#L117
> 
> This will be exported as non-monotonic updown sum I believe which is wrong.

hmm. yeah, you're right. :(

**Review by anuraaga — APPROVED** [review]

**Comment by jkwatson** [comment]
> > @jkwatson not really, https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java#L117
> > This will be exported as non-monotonic updown sum I believe which is wrong.
> 
> hmm. yeah, you're right. :(

https://github.com/open-telemetry/opentelemetry-java/issues/1786 to track getting that fixed.

**Pull request merged**
