### PR TITLE
rename propagator set -> put

### PR DESCRIPTION
**Pull request by thisthat**
This addresses #794

Specification: [link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md#put)

### CODE REVIEW

**Comment by Oberon00** [comment]
Please use the blame view, I think this was an intentional deviation and should be changed in spec instead.

**Comment by bogdandrutu** [comment]
@Oberon00 indeed `put` is more java like when it comes to setting a value in a map :)

**Comment by tylerbenson** [comment]
Issue added here: https://github.com/open-telemetry/opentelemetry-specification/issues/477

**Comment by bogdandrutu** [comment]
Using `set` is correct based on specs

**Pull request closed without merging**
