### PR TITLE
Remove deprecated methods/classes before 1.0 release

### PR DESCRIPTION
**Pull request by bogdandrutu**
Only one deprecated left in metrics, since that package is not going to 1.0 yet.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
we should get rid of the deprecated method in the metrics API as well, since we said we'd get rid of it for 0.13.0

**Review by breedx-splk — APPROVED** [review]
This looks good to me.  Thanks for the deletions!

**Comment by Oberon00** [comment]
Is the trace 1.0 release close?

**Comment by bogdandrutu** [comment]
@jkwatson will do it in a separate PR, a bit more to take care there.

**Review by Oberon00 — APPROVED** [review]
I trust all of these were already deprecated in the latest released version?

**Pull request merged**
