### PR TITLE
Delegate constant traceidratio samplers to the constant implementations.

### PR DESCRIPTION
**Pull request by anuraaga**
Should be equivalent with a bit better performance.

### CODE REVIEW

**Comment by anuraaga** [comment]
Realized we have an attribute set by the ratio sampler too so it's not a 1:1 equivalency.

**Comment by Oberon00** [comment]
@anuraaga Actually I think we should remove that attribute, as it is off-spec (https://github.com/open-telemetry/opentelemetry-specification/pull/570 was never merged). Should I create an issue for that?

**Comment by anuraaga** [comment]
Ah sure sounds good

**Comment by Oberon00** [comment]
Created #2420.

**Pull request closed without merging**
