### PR TITLE
Add Project Status section in README

### PR DESCRIPTION
**Pull request by trivikr**
Fixes: https://github.com/open-telemetry/opentelemetry-java/issues/4611

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
Thanks! Will have @jack-berg also approve when he's back from his vacation.

**Review by chalin — CHANGES_REQUESTED** [review]
Given that the table exists already and is accessible from the website via the [Java page](https://opentelemetry.io/docs/instrumentation/java/), why make a copy, in the README? You're doubling the maintenance effort (multiply that by the number of language SIGs). If you insist on having access to status info from the README, consider adding a link to https://opentelemetry.io/docs/instrumentation/java/.

I'd vote against adding a clone of the docs table.
Thoughts?

/cc @austinlparker @cartermp

**Comment by jkwatson** [comment]
> Given that the table exists already and is accessible from the website via the [Java page](https://opentelemetry.io/docs/instrumentation/java/), why make a copy, in the README? You're doubling the maintenance effort (multiply that by the number of language SIGs). If you insist on having access to status info from the README, consider adding a link to https://opentelemetry.io/docs/instrumentation/java/.
> 
> I'd vote against adding a clone of the docs table. Thoughts?
> 
> /cc @austinlparker @cartermp

Should they be removed from the other language repos that have them as well?

**Comment by austinlparker** [comment]
It'd be nice if each language repo treated the website as authoritative, yes.

**Comment by trivikr** [comment]
Closing because of reason https://github.com/open-telemetry/opentelemetry-java/issues/4611#issuecomment-1185536428

Will create a new PR for linking to language instrumentation link on the website.

**Comment by trivikr** [comment]
Superceded by https://github.com/open-telemetry/opentelemetry-java/pull/4613

**Comment by hdost** [comment]
> It'd be nice if each language repo treated the website as authoritative, yes.

I would agree that having a single (by language) place to manage it is nice. Does it make sense that the Website is that place? Would it be possible to have a macro or something in hugo which pulls in the info from repos? that way it's maintained with the code, but then the website is still upto date.

**Pull request closed without merging**
