### PR TITLE
Do not export counters with no points for OTLP.

### PR DESCRIPTION
**Pull request by carlosalberto**
Potential fix for #1976 

It shows that nothing seems to break with this simple change.

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
LGTM - this seems like a reasonable interpretation of the proto to me

**Comment by jkwatson** [comment]
My only worry is there might be a reason to send an empty payload, just as a heartbeat. Other than that, this looks fine to me.

**Comment by carlosalberto** [comment]
@bogdandrutu Any take on this? 😉

**Comment by carlosalberto** [comment]
Marking this as Ready to Review, in order to get more eyes ;)

**Review by anuraaga — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]

**Comment by jmacd** [comment]
I agree with this as a short-term fix that will make the Java OTLP Metrics export not send what to me is a meaningless point. It's uncovered that we should probably specify in the protocol that a Metric with empty point list may be regarded as equivalent to an absent Metric. If the specification says we can silently drop these Metrics with no data points, then we can assert that this is a correct change.

I would like to bring the Java Metric SDK into more conceptual alignment with the OTel-Go SDK. There we have a `basic` Processor component with two distinct kinds of support that are present in order to implement Prometheus and/or Cumulative metric export pipelines.

1. First, the Processor is the component that is responsible for converting DELTA inputs (from Counter instruments) into CUMULATIVE outputs (i.e., OTLP Metric Sums with AggregationTemporality=CUMULATIVE)
2. Second, the Processor has a "Memory" option that is responsible for maintaining state about every combination of metric instrument and label set that was ever encountered.

Both of these behaviors combine are needed for a Prometheus export pipeline. Only the first of these behaviors is needed for an OTLP/CUMULATIVE export pipeline. None of these behaviors is needed for an OTLP/DELTA export pipeline. Since I'm not familiar with the internals, I don't know how much restructuring is needed to accomplish this goal, but when it is accomplished, there will be a basic Processor component with two optional behaviors. I approve this PR with a TODO mentioning the final state and the need for more SDK specification.

Whether using a CUMULATIVE or DELTA strategy with OTLP, there is no reason to use empty data points. We should either not report a Metric ("no observation(s)") or we should report a Metric with more than zero points ("some observations").

There are independent questions raised here that should not block the resolution of the immediate issue. For example: if a Processor is configured for CUMULATIVE export and not MEMORY behavior, shall we omit those points because of a lack of observations? If the instrument is a SumObserver and the point that was previously observed is later not observed and then subsequently observed again, without changing the start timestamp: what should we make of this? I don't think it's too important what we say about this situation, but in any case we should not be sending Metric values with empty points, right?

@open-telemetry/specs-metrics-approvers  ^^^ some questions for the Metrics specification.

@jkwatson Re: "to send an empty payload, just as a heartbeat". I would advocate for using the memory behavior described here if you need this kind of information. See also https://github.com/open-telemetry/opentelemetry-specification/pull/1102.

**Review by jmacd — APPROVED** [review]

**Comment by jmacd** [comment]
@bogdandrutu I'd like your opinion specifically. See also https://github.com/open-telemetry/opentelemetry-java/issues/1976#issuecomment-722585324

**Comment by carlosalberto** [comment]
@bogdandrutu @jkwatson @jmacd I think we should merge this change, to keep things 'conservative'. Then we can iterate and make this selectable (in order to support Prometheus, for example). Let me know what you think.

**Review by bogdandrutu — APPROVED** [review]
As @jmacd pointed this is a good short term fix.

**Pull request merged**
