### PR TITLE
Remove usages of Develocity and Gradle Enterprise

### PR DESCRIPTION
**Pull request by runningcode**

### CODE REVIEW

**Comment by jkwatson** [comment]
what is the motivation for this PR?

**Comment by runningcode** [comment]
Gradle and the Linux Foundation were not able to come to an agreement on the terms of use. Thus, we need to shut down the Develocity instance.

**Comment by jkwatson** [comment]
@runningcode this PR needs a rebase, and we'd need you to sign the CLA in order to accept this work.

**Comment by jack-berg** [comment]
Superseded by #6903

**Pull request closed without merging**
