### PR TITLE
Expose foreach consumer instead of Entry for baggage.

### LINKED ISSUE #1960: Remove Baggage Entry?
It seems like we can remove `Entry` from baggage package if we change `getEntries` to `forEach` pattern like `Attributes` which would also make them a bit more consistent. However if doing that, it makes me wonder again if `EntryMetadata` is really pulling weight it becomes quite lonely.

### PR DESCRIPTION
**Pull request by anuraaga**
Since sent the tracestate version, figured I'd just go ahead and send this out.

Fixes #1960

### CODE REVIEW

**Comment by carlosalberto** [comment]
Any reason to not keep the `entries()` method, other than the potential removal of `Entry`? 

Although this is very Java-ish, sometimes it feels like an overkill. Also, using `entries()` under Android would also feel better ;)

**Comment by anuraaga** [comment]
I think either implementing `Map` directly, or having `asMap` will be user friendly since they're very familiar interfaces. But they're bigger changes, and until then, I think it's good to avoid entries, at least as currently implemented, as at least it seems better long term as `entrySet` to fit with normal maps. How does that sound?

**Comment by carlosalberto** [comment]
I think it's fine either way, as long as we expose a simple way to return the values (besides the new `forEach()` functionality).

Also, the Specification at this moment requires us to return either a collection or an iterator over the values, so I'd vow for not breaking it. Because of this, I'd prefer if `getEntries()` stay and we discuss the removal of `Entry` a little more.

**Comment by anuraaga** [comment]
Do you think we can add it back after 0.10.0? We want it to be mostly stable for the API, and also want to get it out this week (from what I understand) so I'm focusing on getting semver-breaking API changes in for that. Adding methods afterward shouldn't be a problem though, but I don't want to commit to e.g getEntries vs entrySet vs asMap for now if it's possible as those are names that effect semver.

**Comment by Oberon00** [comment]
What is the advantage of thesis foreach stuff over itertors/collections? From an user-perspective it seems far clunkier.

**Comment by jkwatson** [comment]
I'm not a fan of losing the ability to do Java 8 `Stream` operations on the contents of the `Baggage`. Agree with @Oberon00 that this is a clunkier API. Is it worth introducing that clunkiness just for the sake of consistency with Labels and Attributes?

**Comment by Oberon00** [comment]
Maybe we should actually change labels and attributes to provide some sort of iterator?

**Comment by jkwatson** [comment]
> Maybe we should actually change labels and attributes to provide some sort of iterator?

We could consider adding an iterator, but that would require wrapping each key-value pair in an `Entry` style class, leading to more allocation pressure. I wouldn't want to get rid of the lighter-weight `forEach` for use-cases that are memory sensitive.

**Comment by anuraaga** [comment]
I don't love the foreach either but I do think we should be consistent with the others - is there a difference in memory pressure for baggage / tracestate vs attributes when they're used?

I figured since forEach is consistent with Map, it could provide an easier path to exposing a Map interface in the future. If losing the iterable now and adding later is not palatable, then I'd like to go ahead and expose `entrySet` now instead of getEntries. Does it make sense?

**Comment by carlosalberto** [comment]
> I wouldn't want to get rid of the lighter-weight forEach for use-cases that are memory sensitive.

+1 on that. Although it's not user-friendly, it is supposed to be *only* consumed by SDKs 😉

**Comment by carlosalberto** [comment]
>  then I'd like to go ahead and expose entrySet now instead of getEntries. Does it make sense?

Not a strong opinion, but fine by me.

**Comment by jkwatson** [comment]
After some more reflection, I'm ok with having all the "open telemetry iterable" interfaces work the same way, even if it's a little clunky for the first release. We can always add more options later.

**Review by jkwatson — APPROVED** [review]
Thanks!

**Comment by anuraaga** [comment]
Since #1979 is merged is this ok to merge too? My plan is to then have the tracestate / baggage become arrays, then add a mechanism for them to all expose something like `asMap` or directly implement it.

**Review by jkwatson — APPROVED** [review]
Yes, I think this is the right route for consistency. Being able to model all the various and sundry types as flat lists/arrays internally seems like a win for memory usage overall.

**Comment by jkwatson** [comment]
Discussion at the SIG meeting this morning was to go ahead with this. @carlosalberto was going to log an issue to track being able to access the entries (and assumedly any other `forEach`ables in the project) more directly.

**Comment by Oberon00** [comment]
>  Being able to model all the various and sundry types as flat lists/arrays internally seems like a win

A Map interface can be backed by an array. It would just be a bit of boilerplate code if we would go with that optimization to implement Map on top of a sorted array, but since we only need read-only it should be OK. And before #1944, I think Guava would have that implemented (how does ImmutableMap work?)

**Comment by jkwatson** [comment]
> Oh, it's just a `Collection`? Then `Arrays.asList` would do the job. Collection gives us plenty flexibility already. If we want the option of using a data structure that doesn't know it's size, Iterable would also still be better than the forEach callback.

It's not that simple because the underlying list has alternating entries of keys and values, to reduce allocations.

**Comment by Oberon00** [comment]
OK, then a bit of boilerplate is required, but implementing the Collection interface is no rocket science.

**Pull request merged**
