### PR TITLE
Fix consistency between implementation/test of fromContextOrNull

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
IIRC, sleuth might have needed to differentiate between invalid and null for composite propagator compatibility with Brave, please check if this use can be replaced.

https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/eac53772fc7ca63324da498aaef5ccfec4c28105/spring-cloud-sleuth-otel/src/main/java/org/springframework/cloud/sleuth/otel/propagation/CompositeTextMapPropagator.java#L108

**Comment by bogdandrutu** [comment]
@anuraaga  Sent one PR https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/pull/8 for a different thing, please double check that it is fine :)

> IIRC, sleuth might have needed to differentiate between invalid and null for composite propagator compatibility with Brave, please check if this use can be replaced.

Not sure, we use to have this in our code-base something similar, what did it happen with that?

**Comment by anuraaga** [comment]
> Not sure, we use to have this in our code-base something similar, what did it happen with that?

We removed the shortcircuiting propagator since it's not in spec. For Brave compatibility, sleuth may need short circuiting though, not sure.

**Comment by jkwatson** [comment]
It doesn't bother me to keep these very simple methods in the API. Happy to maintain them, especially if they are useful to someone.

**Review by carlosalberto — APPROVED** [review]

**Comment by anuraaga** [comment]
@bogdandrutu Let's keep the method, but make the implementations of `fromContext` consistent

**Comment by bogdandrutu** [comment]
@jkwatson PR updated

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
