### PR TITLE
Add documentation page for automatic instrumentation

### PR DESCRIPTION
**Pull request by cartermp**
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/972

### CODE REVIEW

**Comment by cartermp** [comment]
Also adding @austinlparker, since this was a discussion topic at the website SIG.

**Comment by jkwatson** [comment]
we had agreed that we would *not* host the auto-instrumentation documentation in this repository. It belongs where the code lives, which is the opentelemetry-java-instrumentation repository.

**Comment by cartermp** [comment]
@jkwatson Oh, interesting. I could see how that's helpful for maintainers. Should the website then figure out a way to source this content from both repositories and then piece them together? It'd be frustrating to have to know to look for the right repository as a user (despite being linked at the bottom of the page, experience with docs in the past has taught me people don't usually look there).

**Comment by jkwatson** [comment]
This reminds me, @anuraaga set up a new repo for combined docs that we should move everything to ASAP. 

opentelemetry-java-docs maybe?

**Comment by jkwatson** [comment]
> Good to know. Happy to help move the docs there, update the otel site, and contribute further. I'm cool with whatever process works best / is easiest to contribute further content to docs.

If you want to PR into that new repo, that would be amazing. Thanks!!

**Comment by austinlparker** [comment]
I mean, if you're factoring the docs out of this repo to begin with, why not just move them all to the website repo...?

**Comment by jkwatson** [comment]
> I mean, if you're factoring the docs out of this repo to begin with, why not just move them all to the website repo...?

We also want to include non-website docs, with runnable code samples and gradle build scripts for them. I don't think that belongs in the website repo, does it?

**Comment by anuraaga** [comment]
Thanks for the help @cartermp. Indeed, we'd like to centralize end-user docs and examples in one place, currently going across the two repos presents a confusing picture.

**Comment by trask** [comment]
@cartermp thanks for helping with this!! I'm going to move the website docs over to the new `opentelemetry-java-docs` repo now, and I'll send a PR to the opentelemetry.io repo to update it to pull in from the new repo. then you can send this PR to the `opentelemetry-java-docs` repo.

**Comment by cartermp** [comment]
Thanks, will do.

**Pull request closed without merging**
