### PR TITLE
Use LongAdder and DoubleAdder instead of atomic variants

### PR DESCRIPTION
**Pull request by tylerbenson**
Now that we're based on Java 8, we can use these instead.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please do the same for Double

**Review by jkwatson — APPROVED** [review]
Thanks! As @bogdandrutu mentioned, the double version would also be nice (could be a separate PR)

**Review by anuraaga — APPROVED** [review]
Sweet

**Comment by jkwatson** [comment]
@tylerbenson needs an unused-import scrub, looks like.

**Pull request merged**
