### PR TITLE
Remove refresh-dependencies for japi

### PR DESCRIPTION
**Pull request by anuraaga**
@jkwatson Do we need to refresh dependencies for this command?

### CODE REVIEW

**Review by kubawach — APPROVED** [review]
LGTM (this was a quick one ;) )

**Comment by jkwatson** [comment]
> @jkwatson Do we need to refresh dependencies for this command?

Yes. Since we use `:latest` as the version for looking up the latest-release, you need to `--refresh-dependencies` for gradle to pick up the actual latest after a release. (assuming you've run this command already before the release)

**Review by jkwatson — CHANGES_REQUESTED** [review]
I don't think we should remove this, due to using the `:latest` version for doing the API diff generation.

**Comment by anuraaga** [comment]
Got it - thanks for clarifying :)

**Pull request closed without merging**
