### PR TITLE
Add throws NPE javadoc to Span addEvent methods

### PR DESCRIPTION
**Pull request by trask**
Thanks for pointing these out @samvaity!

### CODE REVIEW

**Comment by jkwatson** [comment]
Hmm. I wonder if, rather than documenting this, we should fix it so that it doesn't NPE.

**Comment by trask** [comment]
for better or worse, it was documented as NPE in SpanBuilder.addLink():

https://github.com/open-telemetry/opentelemetry-java/blob/7c73ddb158ec39060941be8fafa85240d03c2b70/api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java#L159-L161

**Comment by bogdandrutu** [comment]
@trask we are using the `@Nullable` annotation, so maybe we can make a more general statement that everything that is not marked as `@Nullable` will throw NPE.

**Review by anuraaga — APPROVED** [review]
We're not supposed to throw anywhere in the API, so we do need to fix that. We could merge this first though to reflect the reality for now.

**Comment by jkwatson** [comment]
> We're not supposed to throw anywhere in the API, so we do need to fix that. We could merge this first though to reflect the reality for now.

would it be a breaking change to no longer throw documented NPEs, though? If we don't document them, it can be considered a bug we can fix.

**Comment by anuraaga** [comment]
> would it be a breaking change to no longer throw documented NPEs, though? If we don't document them, it can be considered a bug we can fix.

Ah interesting - I think in general, it's not a breaking change even if it's documented, as long as the replacement is a harmless no-op. But keeping it as a bug, rather than a feature, does make sense too.

**Comment by anuraaga** [comment]
Superceded by #2777, thanks for bringing to attention @trask and @samvaity!

**Pull request closed without merging**
