### PR TITLE
Java

### PR DESCRIPTION
**Pull request by pramodkp295**
Comment 1

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Can you recreate this PR with only the change you would like to merge?

**Comment by jkwatson** [comment]
> Can you recreate this PR with only the change you would like to merge?

Pretty sure this is spam

**Comment by bogdandrutu** [comment]
I would give another few hours, then block the user.

**Comment by 2018CRYPTO** [comment]
Hi Earth?

**Comment by 2018CRYPTO** [comment]
Who are we?
Who am I?
Who are us?
Who are they?

**Pull request closed without merging**
