### PR TITLE
OpenTracing Shim: Store the SpanContextShim in the SpanShim

### PR DESCRIPTION
**Pull request by carlosalberto**
Previously, we had a global map connecting **each** OpenTelemetry `Span` and any linked OpenTracing `SpanContext` - this was done so we could get and set the proper values across different threads, at all times.

However, changes were made recently to its [Specification section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md#span-shim-and-spancontext-shim-relationship) so the OpenTracing `SpanContext` lives directly on the OpenTracing `Span` wrapper, in order to simplify the handling (and removing the map & global lock). This approach will guarantee correctness as long as the entire codebase uses the OpenTracing Shim layer.

There is a warning regarding mixing usage of the OTel API along the OT Shim, just in case:

> As OpenTelemetry is not aware of this association, the related Baggage may not be properly propagated if the
> OpenTelemetry API is consumed along the OpenTracing Shim in the same codebase

cc @zeitlinger

### CODE REVIEW

**Comment by zeitlinger** [comment]
> There is a warning regarding mixing usage of the OTel API along the OT Shim, just in case:
> 
> > As OpenTelemetry is not aware of this association, the related Baggage may not be properly propagated if the
> > OpenTelemetry API is consumed along the OpenTracing Shim in the same codebase

Our current recommendation (in Zalando) is to gradually (library by library) switch from using the shim to OpenTelemetry.
How can we make sure that the baggage is still propagated correctly in this scenario?

**Comment by carlosalberto** [comment]
@zeitlinger Good question. I guess we will have to add lots of new test cases (once I create a follow up to your Baggage PR). In general, your use case will be still supported:

```java
// Baggage.current() != empty/null
// span1 will have Baggage.current() as Baggage.
io.opentracing.Span span1 = createSpan();
```

But the scenarios that _may_ break (hopefully not) people using the shim are:

```java
// Baggage.current() == empty/null
// span1 will have Baggage set to null, explicitly.
io.opentracing.Span span1 = createSpan();

// Activate a non-empty Baggage
try (Scope scope1 = activateBaggage(baggage1)) {
  try (Scope scope = activateSpan(span1)) {
    // Baggage.current() is empty/null,
    // as span1 captured such value at createSpan() time.
  }
}
```

That's besides consuming the `Baggage` from different threads.

**If we find that the current simple but correct behavior doesn't work for you**, we could add a section in the OT compatibility section on explicitly supporting (through a parameter/flag) what we had before, where the associated  `Baggage` for a given `Span` is always visible, from all threads/libraries.

**Comment by zeitlinger** [comment]
@carlosalberto I'm mainly concerned about use cases where the baggage is set using the shim itself, like we do in [this library](https://github.com/zalando/opentracing-toolbox/blob/main/opentracing-flowid/opentracing-flowid/src/main/java/org/zalando/opentracing/flowid/DefaultFlow.java#L55).

**Comment by zeitlinger** [comment]
Yes, I agree :smile:

**Comment by carlosalberto** [comment]
@jkwatson Any chance to also include this in the next release? ;)

**Review by jkwatson — APPROVED** [review]

**Pull request merged**
