### PR TITLE
TracerProvider: Make format settable.

### LINKED ISSUE #718: No way to change HttpTextFormat
There is no way to change the HttpTextFormat in the `TracerSdk`.

https://github.com/open-telemetry/opentelemetry-java/blob/a8d14d8886c7359705710d92e4679b80f8514e93/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java#L34

I know this will probably be reworked with #655 or https://github.com/open-telemetry/oteps/pull/66 but honestly, these look like mid- to long-term projects. So in the meantime it would be great to have a setter for the HttpTextFormat (and probably the BinaryFormat).

### PR DESCRIPTION
**Pull request by Oberon00**
Resolves #718.

### CODE REVIEW

**Comment by carlosalberto** [comment]
I don't think we want this feature to go anymore - based on OTEP 66, now the default `Propagator`s will be set by the API, and the user will be able to override them (removing the instances from both `Tracer` and `CorrelationContext`).

**Comment by Oberon00** [comment]
Hi @carlosalberto, I know this feature is mostly obsoleted by OTEP 66, but it seems that it will take some time until this is implemented, so I wanted to provide this PR as a remedy in the meantime. I do think, however, that we'd want to have the propagators configurable via the builder even after OTEP 66 has landed in java.

**Comment by carlosalberto** [comment]
So we really need OTEP 66 changes for the beta (March 16th). As mentioned in the related PR, now that I have my hands a little free-r, we should be able to keep that feature ready/merged relatively soon (I hope we get most of the things done/ready this week TBH).

I'd put a "Holding on" on this issue while we work on that one, and decide to apply this if for some reason we can't get it merged in 1-2 weeks.

**Comment by bogdandrutu** [comment]
@Oberon00 is this obsolete now?

**Comment by Oberon00** [comment]
I'm not sure. How would you set a custom text format with the new API? I'll look it up.

**Comment by Oberon00** [comment]
That is to say, this PR is certainly obsolete now, but I'll need to check if #718 can be closed.

**Pull request closed without merging**
