### PR TITLE
Use BiConsumer instead of custom interface

### PR DESCRIPTION
**Pull request by bogdandrutu**
Tried to use ObjDoubleConsumer but then it will be inconsistent with the `add` method on the sync instrument.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
are we ok with 
1) boxing all the numeric recordings like this (I think probably yes, since this is async)?
2) handling the possibility of getting `null` passed in with `Long` and `Double` as the types?

**Comment by bogdandrutu** [comment]
are we ok with

> boxing all the numeric recordings like this (I think probably yes, since this is async)?
Probably not a problem.

> handling the possibility of getting null passed in with Long and Double as the types?
Alternative is to use the ObjDoubleConsumer and ObjLongConsumer but unfortunately that will be (Labels, value) which is different than (value, Labels) like in the sync instruments.

I am open to consider that alternative and simplify things.

**Comment by jkwatson** [comment]
If we do keep this as-is, what would the null handling look like? Would we silently drop those recordings? Or default them to 0? I don't think we would want to throw an exception. 

TBH, I wasn't even aware that `ObjDoubleConsumer` and `ObjLongConsumer` existed until you pointed them out! 

I don't have strong feelings either way, as long as we have good documentation on how nulls are handled if we go with the standard BiConsumer.

**Comment by anuraaga** [comment]
I think it's pretty common to define custom interfaces to use a primitive type for a bit of performance and not worrying about null, I lean towards leaving it as is.

**Comment by jkwatson** [comment]
I'm going to close this due to significant drift in the API since it was initially proposed.

**Pull request closed without merging**
