### PR TITLE
Remove helper functions that interact with Context from Tracer and move into contrib

### PR DESCRIPTION
**Pull request by bogdandrutu**
Probably the current `contrib` package should be named `extended-api`

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
so the only way to set span into the scope will be to operate with the context directly? Will context know about spans/have a reference to tracing package?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev just to set into the current "scope" we have `tracer.withSpan(Span)`. The extra functionality of "execute this Runnable with this Span active" is in the contrib package (or extended api).

**Comment by tylerbenson** [comment]
@bogdandrutu can I suggest the method name be `tracer.withSpanInScope(Span)` or just `tracer.inScope(Span)`?  `withSpan` doesn't seem as intuitive to me.  I wouldn't expect it to return a `Scope` just from the method name.  (I'm happy to create an issue for this if you think it's a good idea.)

**Comment by carlosalberto** [comment]
`tracer.withSpanInScope(Span)` is probably too long. I prefer `tracer.withScope()` or `tracer.inScope()`. And yeah, I'd recommend creating a separated ticket for that ;)

**Comment by SergeyKanzhelev** [comment]
@tylerbenson we discussed names at length here https://github.com/open-telemetry/opentelemetry-java/issues/28 Please reactivate an issue if you feel strongly about the name

**Comment by tylerbenson** [comment]
@SergeyKanzhelev thanks for the link.  I am fine with the conclusion of that discussion.  The name is awkward out of context, but I agree it fits in context.

**Pull request merged**
