### PR TITLE
Remove unnecessary LabelValue object.

### PR DESCRIPTION
**Pull request by bogdandrutu**
This PR does not change the functionality/capability of the API, users can still pass null label value if needed, only improves the performance of the current API by reducing an extra allocation for each recorded value.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@songy23 good catch, turned out there were more usages left.

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev do you think we need changes in the specification for this? For the moment I could not find in the specification anything about LabelValue being a standalone object.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu it's OK I think. Just as side note - we have an issue to discuss if we can use the same collections everywhere that may also change something.

**Comment by songy23** [comment]
Please rebase.

**Pull request merged**
