### PR TITLE
Have w3ctracecontextpropagator actually implement textmappropagator.

### PR DESCRIPTION
**Pull request by anuraaga**
Updates https://github.com/open-telemetry/opentelemetry-java/issues/2658

I was expecting a one-word change, woah!

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by Oberon00** [comment]
This weakens encapsulation somewhat. Is this to make the code easier to read?

**Comment by anuraaga** [comment]
@Oberon00 If we could make the class `W3cTraceContextPropagator` non-public, then that is great, but we can't since propagator implementations are separate from the interface. If it's public, there's really no reason for `getInstance` to not return the type - while it's not likely for propagators especially, it does give the option of adding implementation-specific methods if it ever comes up. There isn't really a downside I would say since the class will be exposed either way so is always safe to be ABI-linked against.

**Comment by Oberon00** [comment]
Currently the propagator class is a private inner class. The public class is just the `getInstance` method. But I guess this additional encapsulation is not really much of an advantage in practice.

**Review by jkwatson — APPROVED** [review]
👍  This is fine to change, pre 1.0. Thanks!

**Pull request merged**
