### PR TITLE
Deprecate addSpanProcessor mutator

### PR DESCRIPTION
**Pull request by anuraaga**
Not used in our code anymore.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think before we prove we can pass the tests with the PR I created that global is set once per test and before anyone reads it we are not confident to remove this.

**Comment by jkwatson** [comment]
> I think before we prove we can pass the tests with the PR I created that global is set once per test and before anyone reads it we are not confident to remove this.

Discussion ongoing over in https://github.com/open-telemetry/opentelemetry-java/discussions/2371 Your participation would be very helpful. Thanks!

**Review by jkwatson — APPROVED** [review]
Thanks!

**Comment by jkwatson** [comment]
I'm going to merge this. If we decide we can't remove this due to unforeseen issues, we can un-deprecate it.

**Pull request merged**
