### PR TITLE
Remove Link from API, use SpanData.Link in Sampler

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
What do you think about pulling `Link` up out of the SpanData class, since it's now used for something else aside from Export?

**Comment by bogdandrutu** [comment]
Not sure what is the benefit. Also I want to keep the dependency order the same. The SDK can depend on data but not the other way around

**Comment by bogdandrutu** [comment]
Also I would do later, this one is important to cleanup the API first.

**Comment by jkwatson** [comment]
> Not sure what is the benefit. Also I want to keep the dependency order the same. The SDK can depend on data but not the other way around

I was thinking of keeping it in the data package, just hoisting it up out of the SpanData. The benefit is that it's now used outside the context of SpanData, and so shouldn't be embedded as an auxiliary class in it.

**Review by jkwatson — APPROVED** [review]
API cleanup++
Thanks!

**Pull request merged**
