### PR TITLE
Log warning when duplicate async instruments are registered

### LINKED ISSUE #4005: Log when duplicate async instruments are registered
If I use the API to register two async instruments with the same name, but different callback behavior, the first one registered wins. The callback of the second is never invoked, and there are no logs to tell me that.

For example:
```
    AtomicLong countUp = new AtomicLong(0);
    AtomicLong countDown = new AtomicLong(100);
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countUp.incrementAndGet()));
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countDown.decrementAndGet()));
```

We should provide useful log messages when conflicts like this happen since unlike synchronous instruments, we can't just return the same instrument that was previously registered.

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #4005.

The example in the issue now yields the following results:
```
    AtomicLong countUp = new AtomicLong(0);
    AtomicLong countDown = new AtomicLong(100);
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countUp.incrementAndGet()));
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countDown.decrementAndGet()));

....
WARNING: Found duplicate metric definition: foo
	at unknown source
		To enable better debugging, run your JVM with -Dotel.experimental.sdk.metrics.debug=true
Causes
- InstrumentType [OBSERVABLE_GAUGE] is async and already registered
```

### CODE REVIEW

**Review by kubawach — APPROVED** [review]
Looks good, although codecov complains about new cov < 80% ;)

**Review by jkwatson — APPROVED** [review]

**Comment by jsuereth** [comment]
There's one valid use case of multiple registrations that I would like an answer to (via batch API) before we lock this down.  Specifically, registering callbacks that report different attributes.


```
    AtomicLong countUp = new AtomicLong(0);
    Attributes countUpAttr = ...;
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countUp.incrementAndGet(), countUpAtttr));
    
    AtomicLong countDown = new AtomicLong(100);
    Attributes countDownAttr = ...;
    meter.gaugeBuilder("foo").buildWithCallback(observe -> observe.record(countDown.decrementAndGet(), countDownAttr));
}
```

Nominally, users could just put each observation in a single callback and maybe that's ok.   Just want to make sure we document HOW we want users to do that, especially if we lock down use cases.

**Comment by jack-berg** [comment]
> Nominally, users could just put each observation in a single callback and maybe that's ok. Just want to make sure we document HOW we want users to do that, especially if we lock down use cases.

Small clarification - this PR doesn't change the behavior. If you register multiple callbacks today the first will be called and subsequent ones are silently ignored. This just tries to help users debug why their callback isn't being called. 

I think we have to recommend that for now. An option for users is to use a helper function to transform several callbacks into a composite callback:

```
    meter.gaugeBuilder("foo").buildWithCallback(compositeCallback(
        observer -> observer.record(countUp.incrementAndGet(), upAttrs),
        observer -> observer.record(countDown.incrementAndGet(), downAttrs)
    ));

  ...

  static Consumer<ObservableDoubleMeasurement> compositeCallback(
      Consumer<ObservableDoubleMeasurement>... callbacks) {
    return observer -> {
      for (Consumer<ObservableDoubleMeasurement> callback : callbacks) {
        callback.accept(observer);
      }
    };
  }
```

**Comment by jack-berg** [comment]
There's an outstanding issue related to registering multiple async callbacks [here](https://github.com/open-telemetry/opentelemetry-java/issues/3549).

I believe its possible to support this type of use case by. We'd simply have to make `AsynchronousMetricStorage` instances mutable such that when another callback is registered for the same instrument, that the storage is updated to have a callback which is a composite of the original and the new. 

However, the issue references that the spec is the limiting factor right now, which is likely due to the [following section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument):

> Meter implementations MUST return an error when multiple Instruments are registered under the same Meter instance using the same name.

Thinking about it more and my other [comment](https://github.com/open-telemetry/opentelemetry-java/pull/4020#issuecomment-1001713645), a user could implement their own mutable callback to solve that problem. For example:

```
    MutableCallback mutableCallback = new MutableCallback();
    meter.gaugeBuilder("foo").buildWithCallback(mutableCallback);
    mutableCallback.add("up", observer -> observer.record(countUp.incrementAndGet(), upAttrs));
    mutableCallback.add("down", observer -> observer.record(countDown.decrementAndGet(), downAttrs));

  ...

  static class MutableCallback implements Consumer<ObservableDoubleMeasurement> {
    private final Map<String, Consumer<ObservableDoubleMeasurement>> callbacks = new HashMap<>();

    void add(String id, Consumer<ObservableDoubleMeasurement> callback) {
      callbacks.put(id, callback);
    }

    void remove(String id) {
      callbacks.remove(id);
    }

    @Override
    public void accept(ObservableDoubleMeasurement observable) {
      List<Consumer<ObservableDoubleMeasurement>> callbacksCopy = new ArrayList<>(callbacks.values());
      for (Consumer<ObservableDoubleMeasurement> callback : callbacksCopy) {
        callback.accept(observable);
      }
    }
  }
```

**Comment by mateuszrzeszutek** [comment]
> There's one valid use case of multiple registrations that I would like an answer to (via batch API) before we lock this down. Specifically, registering callbacks that report different attributes.

Just for the record, I've encountered exactly this case in my Micrometer instrumentation -- ended up implementing a mutable composite callback, works fine; especially when you have to stop/remove certain measurements.

**Review by anuraaga — APPROVED** [review]
Let's get this logging in, and if we do in the future allow multiple callbacks even with the same API, it would be accepting more input than before by removing the log message and a semver-comaptible change

**Pull request merged**
