### PR TITLE
Remove link and parent sampling decision from Probability sampler

### LINKED ISSUE #1225: Probability sampler only respects positive parent decision
~According to [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/18b2752ebe6c7f0cdd8c7b2bcbdceb0ae3f5ad95/specification/trace/sdk.md#built-in-samplers), the probability sampler's "default behavior should be to trust the parent `SampledFlag`"~ (EDIT: See https://github.com/open-telemetry/opentelemetry-java/issues/1225#issuecomment-668224260). However, in Java, the decision is only respected if sampled=true. If sampled=false, the trace is potentially restarted with the sampler's probability. IMHO, notwithstanding any spec-conformance, this behavior is very weird and surprising.

The responsible condition is this:
https://github.com/open-telemetry/opentelemetry-java/blob/d7f6d5a64176b44752bbd4bd403716a0f150b3e6/sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java#L195

### PR DESCRIPTION
**Pull request by thisthat**
Fixes #1225

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Nice

**Comment by jkwatson** [comment]
I think this is a good change, but I have a concern. Right now, if you configure the trace config with a probability, it won't wrap it in a ParentOrElse sampler, even though it starts out that way. This means that a simple config change to change the default probability will have a knock-on effect of also no longer considering the parent's sampling state. 

I think we need to get that bit fixed before we can merge this change. Either, we need to not use the ParentOrElse sampler by default, or we need to always use it when the config is used to change the sampling probability.

**Comment by jkwatson** [comment]
This is the blocking issue:  https://github.com/open-telemetry/opentelemetry-java/issues/1526

**Comment by thisthat** [comment]
@jkwatson I see your point but I think this is not strictly related to the changes introduced by this PR. This PR is about the probability sampler behavior alone whereas #1526 is about changing either the returned object by `Samplers.probability(double)` or https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java#L303

**Comment by jkwatson** [comment]
If we merge this, we will break existing users who are expecting the parent-logic to work, with a non-100% probability sampler. I'd like to not leave the system in a state where you can't get the existing behavior.

**Comment by thisthat** [comment]
> If we merge this, we will break existing users who are expecting the parent-logic to work, with a non-100% probability sampler. I'd like to not leave the system in a state where you can't get the existing behavior.

Fair point! :)

**Comment by jkwatson** [comment]
@thisthat I think that #1595 should unblock this. Please take a look.

**Comment by thisthat** [comment]
Thank you @jkwatson! I'll have a look and update the PR accordingly

**Comment by thisthat** [comment]
@jkwatson I have rebased and update the PR. Please, have another look if everything is correctly in place now :)

**Review by jkwatson — APPROVED** [review]
Thanks!

**Pull request merged**
