### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davebarda**
Changed "collector" to "agent" (As usually agent is set on the localhost and not the collector)

### CODE REVIEW

**Comment by jkwatson** [comment]
It looks like you did the opposite of what your PR description says. Intentional?

**Comment by davebarda** [comment]
Updated..

**Comment by carlosalberto** [comment]
cc @pavolloffay

**Comment by jkwatson** [comment]
@davebarda can you rebase this against master, to make sure the build is ok?

**Pull request merged**
