### PR TITLE
[Breaking Change] Limit the public api in the Context package

### PR DESCRIPTION
**Pull request by bogdandrutu**
Avoid exposing the public classes for StrictContextStorage, but preserve the functionality as it was protected by a "flag". This will give users the same experience as before and will allow us to move forward by improving the code without having to deal with ABI compatibility.

Part of this PR I had to remove 2 test classes which I will take as an action item to fix that and re-add them after this PR is merged, also I copied the `WeakConcurrentMap` in the jfr extension for the moment until we clarify where this code can leave so that multiple packages can share this.

Summary:
* Copying the `WeakConcurrentMap` and not exposing it publicly should not be considered breaking change, because no external user should depend on that.
* I do not believe that it was expected for users to consume directly `StrictContextStorage`, it was also final so could not be extended. So making this package protected should not be consider breaking change for the users.
* Counted the number of lines (not including tests and propagation) in the context package, we have ~900 lines in StrictContextStorage/AbstractWeakConcurrentMap/WeakConcurrentMap and ~950 all the other classes and interfaces. I think limiting the number of lines that we expose public is a clear win, and we don't break the users.

Fixes https://github.com/open-telemetry/opentelemetry-java/issues/2735

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
I don't think this matters very much, as the number of users who will ever care is very very small. So, I would prefer not making further changes this close to 1.0.0.

**Comment by bogdandrutu** [comment]
I think if it is has so little users is not been better to not have it

**Comment by jkwatson** [comment]
I don't want to make changes on short notice, destabilizing what we have right now, that is working just fine.

**Comment by bogdandrutu** [comment]
To document the reason: maintainers voted no against this change

**Pull request closed without merging**
