### PR TITLE
Remove all APIs that allow passing context or other entries from the Context.

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@songy23 we already have a direct dependency and we may need to address that separately. We do pass the Context because we don't want users to pass distContext + SpanContext also this removes the dependency between metrics and trace.

**Comment by bogdandrutu** [comment]
In the second example you will call the version without any context because that automatically records against the current context.

But I do see some concerns here, also some advantages we can read from multiple entries from the context and also we don't have a dependency on these entries in the api

**Comment by songy23** [comment]
> In the second example you will call the version without any context because that automatically records against the current context.

That's true, but under the hood we still rely on gRPC to create a new instance of `Context` with attaching the given `DistritbutedContext` (since `Context` is immutable). That yields an extra object allocation compared to the first example. In other words, with the new API whenever we want to record metrics against additional entries, we'll create a temporary `Context` which copies everything from its parent but only lives for a very short period of time.

May be an implementation detail but something worth considering :)

**Comment by bogdandrutu** [comment]
@songy23 we also do have the label keys/values (and Handles) for this case. So not sure if for a key/value is worth putting it in the Context if actually we don't want it in the Context. So we can use the Handles and have these extra labels.

**Comment by bogdandrutu** [comment]
@songy23 
>  we'll create a temporary Context which copies everything from its parent but only lives for a very short period of time.

That is not true, the way how it works is saving a parent pointer, and only the values that changed are copied.

**Comment by bogdandrutu** [comment]
@songy23 while I like arguing with you, let me just remove for the moment all methods that accept Context until we decide on that.

**Comment by bogdandrutu** [comment]
@songy23 we cannot shade grpc-context. If we do shade that we cannot share the same context between different libraries that use the context (for different other entries), also the in-process propagation will not work because callbacks will not be wrapped with the shaded version.

**Comment by adriancole** [comment]
you can shade  or otherwise provide an internal copy of grpc context. just you want to prefer grpc when it is available. this means an interface with platform lookup similar to how grpc context internally works to find storage or brave's platform type

**Pull request merged**
