### PR TITLE
Add helper context propagation for guava callbacks

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by jkwatson** [comment]
This module only seems to be tangentially related to OpenTelemetry. It's more of a grpc-context contrib module. Does it belong in the open telemetry project at all?

**Comment by carlosalberto** [comment]
Although I think this is a very nice addition, I also feel this is not quite close related to OpenTelemetry itself.

**Comment by bogdandrutu** [comment]
This will be needed for the auto-instrumentation at least. @zhangkun83 do you think we can have these helpers in grpc-contrib?

**Comment by zhangkun83** [comment]
I will defer to @ejona86

**Comment by trask** [comment]
I'm still really hopeful that the `grpc-context` dependency will be removed from `opentelemetry-api` (#575)

**Comment by bogdandrutu** [comment]
@trask can you tell me why?

**Comment by trask** [comment]
Why I'm hopeful that the `grpc-context` dependency will be removed from `opentelemetry-api`:

* My fear of gRPC version conflicts
* I think we will have better success getting libraries (e.g. say Apache HTTPClient) to natively depend on `opentelemetry-api` if it does not transitively pull in gRPC (because other libraries will be afraid introducing version conflicts to their users)
* Context propagation seems like a really core part of the OpenTelemetry charter, so depending on gRPC for this doesn't seem quite right to me. It seems like the ideal end state is for it to be the other way around, with OpenTelemetry defining library-neutral context propagation, and gRPC depending on OpenTelemetry's context propagation.

**Comment by bogdandrutu** [comment]
@ejona86 I am fine to make the proposed changes in terms of code, but for the moment I am looking into a place where to host this functionality. Can you make a decision where in gRPC you want to have this, and will make a PR and try to address the code changes feedback.

**Pull request closed without merging**
