### PR TITLE
Add APIs to determine if tracer, logger, instruments are enabled

### PR DESCRIPTION
**Pull request by jack-berg**
Followup to #6497.

Spec PRs https://github.com/open-telemetry/opentelemetry-specification/pull/4063 and https://github.com/open-telemetry/opentelemetry-specification/pull/4020 extended the SDK scope config options with corresponding APIs, which can be called to avoid unnecessary computation recording telemetry when the SDK isn't going to do anything with it.

### CODE REVIEW

**Comment by jack-berg** [comment]
Good call! Resolved.

**Comment by jkwatson** [comment]
Is the title of this PR correct? Is this just a stepping stone toward being able to have API disabled via some sort of configuration, per scope?

**Comment by jack-berg** [comment]
There's already (experimental) SDK config to disable scopes. This adds (experimental) API surface area which allows instrumentation to inspect whether a scope is disabled, and if yes, avoid unnecessary computation in recording instrumentation.

The idea of having easier SDK configuration for disabling these (i.e. file config, or something else) is independent and not addressed by this.

**Comment by jkwatson** [comment]
> There's already (experimental) SDK config to disable scopes. This adds (experimental) API surface area which allows instrumentation to inspect whether a scope is disabled, and if yes, avoid unnecessary computation in recording instrumentation.
> 
> The idea of having easier SDK configuration for disabling these (i.e. file config, or something else) is independent and not addressed by this.

So...is the title of this PR incorrect, then?

**Comment by jack-berg** [comment]
> So...is the title of this PR incorrect, then?

I'm not following.. This PR does add an API to check if a particular scope is enabled.

**Comment by jkwatson** [comment]
> > So...is the title of this PR incorrect, then?
> 
> I'm not following.. This PR does add an API to check if a particular scope is enabled.



> > So...is the title of this PR incorrect, then?
> 
> I'm not following.. This PR does add an API to check if a particular scope is enabled.

It might do that indirectly; what it does is add APIs to see if a given tracer/instrument/logger is enabled. Those _can_ be scope associated, but don't have to be. /shrug

**Comment by jack-berg** [comment]
> It might do that indirectly; what it does is add APIs to see if a given tracer/instrument/logger is enabled. Those can be scope associated, but don't have to be. /shrug

Ahh I see. We're talking past each other on language. I use the phrase "scope" to refer to the concept of tracer / logger / meter collectively, since tracer / logger / meter are the signal-specific terms for scope. Admittedly, its a bit imprecise. I'll update the PR title.

**Review by jkwatson — APPROVED** [review]

**Comment by jack-berg** [comment]
> What API will actually allow users to enable/disable these things, BTW?

An experimental API for this already exists. See [ScopeConfiguratorTest](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/all/src/test/java/io/opentelemetry/sdk/ScopeConfiguratorTest.java), [LoggerConfigTest](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/logs/src/test/java/io/opentelemetry/sdk/logs/LoggerConfigTest.java), [MeterConfigTest](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/MeterConfigTest.java), [TracerConfigTest](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/test/java/io/opentelemetry/sdk/trace/TracerConfigTest.java) for usage details.

Ergonomics will improve once the API is stabilized.

**Pull request merged**
