### PR TITLE
Update to Gradle 7.2

### PR DESCRIPTION
**Pull request by anuraaga**
And try ubuntu-20.04.

@jkwatson I tried incorporating #3568 into this to see how it goes, mainly since I know it won't use the build cache at all.

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]

**Comment by anuraaga** [comment]
@jkwatson Hmm can confirm I don't see them either. Manually editing the DOM in Chrome inspector didn't work either 😂

**Comment by jkwatson** [comment]
> @jkwatson Hmm can confirm I don't see them either. Manually editing the DOM in Chrome inspector didn't work either 😂

I wonder if merging this might force the issue. We can always manually merge after checking what's passed until that bug is fixed.

**Comment by anuraaga** [comment]
> I wonder if merging this might force the issue. We can always manually merge after checking what's passed until that bug is fixed.

Yeah I had that thought to. Let's try it

**Comment by anuraaga** [comment]
@jkwatson I went ahead and removed the required status check on ubuntu-18.04. And now that can't be restored, searching in the checks only shows Build (macos-*). The GitHub bug appears to be something like only items that are already in the list are presented in the autocompletion...

**Comment by jkwatson** [comment]
Ugh. A little more work for us until that gets fixed. Has anyone logged it with github  yet?

**Pull request merged**
