### PR TITLE
Use standard ArrayList size rather than max number of links for initial span links allocation

### PR DESCRIPTION
**Pull request by johnbley**
Most spans that have links don't grow to contain the maximum number of links [Citation needed].  So, when faulting in a `links` list to hold them, there's no need to assume we'll need memory to hold the maximum.

### CODE REVIEW

**Review by breedx-splk — COMMENTED** [review]
I'm curious to see this benchmarked against an implementation that uses `LinkedList`, especially in cases for:
* no links (min)
* 11 links 
*  128 links (max)

**Comment by johnbley** [comment]
> * no links (min)

For no links, this is faulted in, so any data structure's `null` is equally performant.  I'm not sure I'd care to guess about the numerical distribution of any particular telemetry structure, much less tune to it.  I'm pretty certain, however, that most spans don't reach the max number of links.

**Comment by jkwatson** [comment]
I'd like to see before/after benchmarks for a variety of cases before changing this.

**Review by trask — APPROVED** [review]
this seems the right thing to do for me even without benchmarks

**Review by jack-berg — COMMENTED** [review]
> this seems the right thing to do for me even without benchmarks

I agree

**Review by jack-berg — APPROVED** [review]

**Comment by breedx-splk** [comment]
I see where @trask and @jack-berg are coming from, and I don't want my ask to be a blocker. This is still probably a net improvement. I'm just a little hung up on the idea that a certain use case (messaging?) could generate lots of spans with ~11 links, which then requires one allocation for the first link and then another for the grow at 10. 🤷🏻

**Comment by johnbley** [comment]
> generate lots of spans with ~11 links

Fair question.  The maximal case I can think of is a lambda triggered by an sqs message, with xray links turned on, and somehow the http-level invocation also carries b3, jaeger, and opentracing headers configured to be attached as links, which doesn't get anywhere near 11 links.  I grepped for `addLinks` and `SpanLinksBuilder` usage in `opentelemetry-java-instrumentation` and didn't see anything that operated in a loop or in batch.

**Comment by laurit** [comment]
I also think this is a reasonable change. As for using a linked list, here is what Josh Block has to say about it https://twitter.com/joshbloch/status/583813919019573248?lang=en

**Review by laurit — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]
seems fine. a few bytes saved per span seems like an ok incremental improvement.

**Pull request merged**
