### PR TITLE
Add benchmark for recording exception on a span

### PR DESCRIPTION
**Pull request by iNikem**
Results from my machine demonstrate that recording exception may be quite an expensive operation:

```
Benchmark                                                                     Mode  Cnt      Score      Error   Units
ExceptionBenchmark.createException                                            avgt   10   1043.408 ±   52.696   ns/op
ExceptionBenchmark.createException:·gc.alloc.rate                             avgt   10    438.773 ±   23.161  MB/sec
ExceptionBenchmark.createException:·gc.alloc.rate.norm                        avgt   10    720.000 ±    0.001    B/op
ExceptionBenchmark.createException:·gc.churn.G1_Eden_Space                    avgt   10    442.504 ±  129.812  MB/sec
ExceptionBenchmark.createException:·gc.churn.G1_Eden_Space.norm               avgt   10    724.855 ±  193.585    B/op
ExceptionBenchmark.createException:·gc.churn.G1_Old_Gen                       avgt   10      0.020 ±    0.046  MB/sec
ExceptionBenchmark.createException:·gc.churn.G1_Old_Gen.norm                  avgt   10      0.034 ±    0.078    B/op
ExceptionBenchmark.createException:·gc.churn.G1_Survivor_Space                avgt   10      0.266 ±    1.274  MB/sec
ExceptionBenchmark.createException:·gc.churn.G1_Survivor_Space.norm           avgt   10      0.440 ±    2.104    B/op
ExceptionBenchmark.createException:·gc.count                                  avgt   10     22.000             counts
ExceptionBenchmark.createException:·gc.time                                   avgt   10     21.000                 ms
ExceptionBenchmark.createSpan                                                 avgt   10    453.535 ±   46.864   ns/op
ExceptionBenchmark.createSpan:·gc.alloc.rate                                  avgt   10    461.407 ±   48.407  MB/sec
ExceptionBenchmark.createSpan:·gc.alloc.rate.norm                             avgt   10    328.000 ±    0.001    B/op
ExceptionBenchmark.createSpan:·gc.churn.G1_Eden_Space                         avgt   10    443.071 ±  128.458  MB/sec
ExceptionBenchmark.createSpan:·gc.churn.G1_Eden_Space.norm                    avgt   10    315.730 ±   91.491    B/op
ExceptionBenchmark.createSpan:·gc.churn.G1_Old_Gen                            avgt   10      0.006 ±    0.020  MB/sec
ExceptionBenchmark.createSpan:·gc.churn.G1_Old_Gen.norm                       avgt   10      0.004 ±    0.013    B/op
ExceptionBenchmark.createSpan:·gc.churn.G1_Survivor_Space                     avgt   10      0.265 ±    1.269  MB/sec
ExceptionBenchmark.createSpan:·gc.churn.G1_Survivor_Space.norm                avgt   10      0.172 ±    0.822    B/op
ExceptionBenchmark.createSpan:·gc.count                                       avgt   10     22.000             counts
ExceptionBenchmark.createSpan:·gc.time                                        avgt   10     18.000                 ms
ExceptionBenchmark.createSpanAndRecordException                               avgt   10  12022.184 ±  548.125   ns/op
ExceptionBenchmark.createSpanAndRecordException:·gc.alloc.rate                avgt   10   1153.336 ±   52.255  MB/sec
ExceptionBenchmark.createSpanAndRecordException:·gc.alloc.rate.norm           avgt   10  21824.005 ±    0.001    B/op
ExceptionBenchmark.createSpanAndRecordException:·gc.churn.G1_Eden_Space       avgt   10   1150.708 ±  147.878  MB/sec
ExceptionBenchmark.createSpanAndRecordException:·gc.churn.G1_Eden_Space.norm  avgt   10  21756.995 ± 2271.406    B/op
ExceptionBenchmark.createSpanAndRecordException:·gc.churn.G1_Old_Gen          avgt   10      0.002 ±    0.003  MB/sec
ExceptionBenchmark.createSpanAndRecordException:·gc.churn.G1_Old_Gen.norm     avgt   10      0.043 ±    0.048    B/op
ExceptionBenchmark.createSpanAndRecordException:·gc.count                     avgt   10     57.000             counts
ExceptionBenchmark.createSpanAndRecordException:·gc.time                      avgt   10     29.000                 ms
```

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Just for reference, we also have `PrintThrowableBenchmark` which I suspect is similar timing to the recordException one. But it's still interesting having these three to compare against.

I had created an optimized print writer in the past which doesn't synchronize and could reuse `ThreadLocal<StringBuilder>`, dropped it at the time to reduce complexity but might be time to bring it back. Not that it'll get fast or anything, but at least less slow.

**Comment by jkwatson** [comment]
At the very least, we could probably get the expensive bit off the hot path and do it when converting to SpanData, rather than in-line.

**Comment by jkwatson** [comment]
Is 12µs all that bad? That seems pretty reasonable to me. Or are you worried about allocations?

**Comment by iNikem** [comment]
I am worried about allocations here :)

**Comment by jkwatson** [comment]
> I am worried about allocations here :)

oh, well, then hot path/cool path won't make any difference, I guess. :(

**Review by jkwatson — APPROVED** [review]

**Pull request merged**
