### PR TITLE
Update proto to the latest commit

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by Oberon00** [comment]
Shouldn't we wait for the imminent tagged release in opentelemetry-proto? https://github.com/open-telemetry/opentelemetry-proto/pull/133

**Comment by bogdandrutu** [comment]
We can do that, but all PRs in the proto will be around releasing instructions and changelog etc. This PR updates the core to use the latest changes, so I see your point of needing another PR to use the tag but that will be just a submodules sync. No strong opinion

**Comment by Oberon00** [comment]
My comment was no strong opinion either. 😃 I just thought that it that since we don't have any particular reason to update now (I think the proto stayed wire-compatible over this change), we can just as well switch to only updating to proper releases.

**Comment by bogdandrutu** [comment]
@Oberon00 done, now synced to v0.3.0

**Pull request merged**
