### PR TITLE
Rename ProbabilitySampler to TraceIdRatioBased

### PR DESCRIPTION
**Pull request by dengliming**
closes [https://github.com/open-telemetry/opentelemetry-java/issues/1573](https://github.com/open-telemetry/opentelemetry-java/issues/1573)

### CODE REVIEW

**Comment by jkwatson** [comment]
There's also the `Samplers.Probability` to rename. Thanks!

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Thanks for the help @dengliming!

**Comment by jkwatson** [comment]
@dengliming It looks like something is amiss with the CLA; like maybe one of the commits is missing a username. Maybe a rebase squashing that commit might fix it up?

**Comment by dengliming** [comment]
move to [https://github.com/open-telemetry/opentelemetry-java/pull/1666](https://github.com/open-telemetry/opentelemetry-java/pull/1666)

**Pull request closed without merging**
