### PR TITLE
Mark opentracing-shim as stable

### PR DESCRIPTION
**Pull request by jack-berg**
cc @carlosalberto

### CODE REVIEW

**Comment by carlosalberto** [comment]
cc @tylerbenson for an additional review

**Review by tylerbenson — APPROVED** [review]
There are parts of the code that could use some more comments (for example `TracerShim.maybeUnobfuscate`.  I think the readme could also use a section to document some of the incongruences between the APIs, for example in OTel baggage is immutable.
I don't think these prevent marking it as stable though.

**Comment by jack-berg** [comment]
@carlosalberto / @jkwatson I think this is ready to go and is low risk given the tiny API surface area, but we lack approvals required to merge for May release.

**Review by jkwatson — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Comment by carlosalberto** [comment]
Thanks for raising this @jack-berg !

**Pull request merged**
