### PR TITLE
Consistent naming of SDK implementation classes

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jkwatson** [comment]
I think in the original rename PR, we had decided to keep this one the same. This is, in some sense, the SDK proper, and I so I don't think it makes sense to use "Sdk" as a modifier in this case. 

The other ones that were renamed are the "SDK"'s implementation of the interfaces, and thus the thing (eg. Tracer) is modified by "Sdk" making "SdkTracer".

**Comment by bogdandrutu** [comment]
> The other ones that were renamed are the "SDK"'s implementation of the interfaces, and thus the thing (eg. Tracer) is modified by "Sdk" making "SdkTracer".

OpenTelemetrySdk is indeed an implementation of the OpenTelemetry interface correct?

**Comment by iNikem** [comment]
I always felt that "SdkTracer" == "SDK's Tracer" == "Tracer of SDK". By the same logic "SDK of OpenTelemetry" == "OpenTelemtry's SDK" == "OpenTelemetrySdk".

**Comment by bogdandrutu** [comment]
@iNikem it is very confusing to have half of the class names prefix with `Sdk` and the other half suffix with `Sdk`. Users will get very confused by this pattern, I am trying to offer a consistent experience, all SDK instances are prefixed with `Sdk`

**Comment by iNikem** [comment]
@bogdandrutu there is ONE class with `Sdk` suffix. But I am not a maintainer of this repo :) As a user I find `SdkTracer` and `OpenTelemetrySdk` quite intuitive.

**Comment by anuraaga** [comment]
Agree with @iNikem I'd lean towards having just this one class suffix with SDK, since it corresponds well with what we always call the "OpenTelemetry SDK".

**Comment by jkwatson** [comment]
the majority seem ok with leaving this as-is, so I'm closing this PR.

**Pull request closed without merging**
