### PR TITLE
Rename Blank SpanContext to Invalid.

### PR DESCRIPTION
**Pull request by songy23**
Fixes https://github.com/open-telemetry/opentelemetry-java/issues/380.

### CODE REVIEW

**Comment by songy23** [comment]
Would like to hear opinions on the naming.

**Comment by pavolloffay** [comment]
+1 invalid is more descriptive than blank (if it is semantically invalid of course).

**Comment by carlosalberto** [comment]
For the record: I remember us making this component package private, as we didn't want to expose it to the end user. Maybe @yurishkuro remembers too? ;)

**Comment by songy23** [comment]
> For the record: I remember us making this component package private, as we didn't want to expose it to the end user. 

`DefaultSpan` is being used in a different package (`trace.unsafe`) so it needs to be public. Otherwise we'll have to add a noop span implementation in `trace.unsafe`.

**Comment by bogdandrutu** [comment]
Please rebase.

**Comment by bogdandrutu** [comment]
@carlosalberto about exposing or not this, please file a separate issue. this PR is focused on the name.

**Comment by songy23** [comment]
Rebased, PTAL.

**Comment by bogdandrutu** [comment]
@songy23 Please open an issue for @carlosalberto comment.

**Pull request merged**
