### PR TITLE
Move api/context to context.

### PR DESCRIPTION
**Pull request by anuraaga**
Reflects package name

### CODE REVIEW

**Comment by jkwatson** [comment]
gah! why does github make this look like a ton of new classes, rather than just moves?

**Comment by jkwatson** [comment]
> gah! why does github make this look like a ton of new classes, rather than just moves?

and now github has sorted it out and makes it easy. 😕

**Comment by jkwatson** [comment]
I'm totally fine with this, but I'd also like to make sure that @bogdandrutu is ok, so we don't move it again. :)

**Review by jkwatson — APPROVED** [review]

**Comment by bogdandrutu** [comment]
I think the maven artifact is ":context" so probably we can stick with this path.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
