### PR TITLE
Nit: move Context as first argument to SpanProcessor.onStart

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by Oberon00** [comment]
Why is this order better than the previous?

**Comment by bogdandrutu** [comment]
@Oberon00 probably too much `golang` in the past few months, but I feel it more natural :) also as the title says is a nit.

**Review by carlosalberto — APPROVED** [review]

**Comment by carlosalberto** [comment]
Don't have a strong feeling around this, but overall I like it.

**Review by jkwatson — APPROVED** [review]
No strong opinion one way or another, but it definitely does make it a little more like golang. ;)

**Comment by trask** [comment]
fwiw, this matches instrumentation repo: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1360#issuecomment-711481565

**Review by anuraaga — APPROVED** [review]
Thanks!

**Pull request merged**
