### PR TITLE
Enable tooling for mrjar and use it to get epoch time in best way for…

### LINKED ISSUE #1527: Use microsecond precision on Java 9+
A small amount of version detecting would let us have better precision on timestamps (I don't think I see this anywhere here yet), a couple of examples

https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/internal/Platform.java#L166
https://github.com/line/armeria/blob/0bb591d252884ec471af00e2757032ae57196d5e/core/src/main/java9/com/linecorp/armeria/internal/common/Java9VersionSpecific.java#L40

### PR DESCRIPTION
**Pull request by anuraaga**
… Java 8 or 9+.

Fixes #1527

### CODE REVIEW

**Comment by Oberon00** [comment]
I'm a bit worried about how this MultiJar feature will play with tooling such as the shadow gradle plugin that the auto-instrumentation uses. Will shadow be able to correctly handle classes added under META-INF, e.g. will it patch the classes there when asked to? E.g. the auto-instrumenting agent does this for java.util.logging.

**Review by jkwatson — APPROVED** [review]
Thanks!

**Comment by anuraaga** [comment]
@Oberon00 Will require verification but I see support for it here https://github.com/johnrengelman/shadow/pull/526/files

**Comment by jkwatson** [comment]
> @Oberon00 Will require verification but I see support for it here https://github.com/johnrengelman/shadow/pull/526/files

So, if we merge, can you verify before we do a release?

**Comment by anuraaga** [comment]
@jkwatson Yup will check it

**Pull request merged**
