### PR TITLE
Remove unnecessary string allocation on hot path

### PR DESCRIPTION
**Pull request by iNikem**
Benchmark results before (pay special to attention to `gc.alloc.rate.norm`):

```
Benchmark                                                    Mode  Cnt     Score     Error   Units
SpanIdBenchmark.getSpanIdBytes                               avgt   15    66.128 ±   0.299   ns/op
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate                avgt   15  6367.137 ±  28.810  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate.norm           avgt   15   664.000 ±   0.001    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space       avgt   15  6373.704 ± 159.516  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space.norm  avgt   15   664.673 ±  15.814    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Old_Gen          avgt   15     0.011 ±   0.004  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Old_Gen.norm     avgt   15     0.001 ±   0.001    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.count                     avgt   15   267.000            counts
SpanIdBenchmark.getSpanIdBytes:·gc.time                      avgt   15   147.000                ms
```

After:
```
Benchmark                                                    Mode  Cnt    Score    Error   Units
SpanIdBenchmark.getSpanIdBytes                               avgt   15   17.189 ±  0.084   ns/op
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate                avgt   15  885.418 ±  4.361  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.alloc.rate.norm           avgt   15   24.000 ±  0.001    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space       avgt   15  897.040 ± 55.715  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Eden_Space.norm  avgt   15   24.313 ±  1.448    B/op
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Old_Gen          avgt   15    0.003 ±  0.002  MB/sec
SpanIdBenchmark.getSpanIdBytes:·gc.churn.G1_Old_Gen.norm     avgt   15   ≈ 10⁻⁴             B/op
SpanIdBenchmark.getSpanIdBytes:·gc.count                     avgt   15   92.000           counts
SpanIdBenchmark.getSpanIdBytes:·gc.time                      avgt   15   39.000               ms
```

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
Great catch! How many other little gotchas like this are lurking in the codebase, I wonder?

**Review by breedx-splk — APPROVED** [review]
Yeah this is a really nice catch!  I wonder about the additional possibility of just removing the validation check entirely, but people like that safety....  👍🏻

**Comment by kubawach** [comment]
Nice! Simple and elegant.

**Review by anuraaga — APPROVED** [review]
Yikes, thanks!

**Comment by trask** [comment]
@iNikem 💯

**Pull request merged**
