### PR TITLE
Fix missing unsafe available check

### PR DESCRIPTION
**Pull request by laurit**
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/6913

### CODE REVIEW

**Review by trask — COMMENTED** [review]
is it worth (possible?) adding something in CI that runs the tests without unsafe?

**Review by breedx-splk — APPROVED** [review]

**Comment by laurit** [comment]
> is it worth (possible?) adding something in CI that runs the tests without unsafe?

added a test that uses a custom class loader to hide sun.misc.Unsafe from the tested code

**Review by jack-berg — APPROVED** [review]

**Comment by jack-berg** [comment]
Thanks for the fix!

**Comment by io7m** [comment]
Can confirm this fixes the issue. :+1:

**Comment by trask** [comment]
> > is it worth (possible?) adding something in CI that runs the tests without unsafe?
> 
> added a test that uses a custom class loader to hide sun.misc.Unsafe from the tested code

ah I see the problem with using something like `--sun-misc-unsafe-memory-access=deny` is that then gradle/kotlin itself fails 😢

> Caused by: java.lang.UnsupportedOperationException: objectFieldOffset
>        at org.jetbrains.kotlin.com.intellij.util.containers.Unsafe.objectFieldOffset(Unsafe.java:126)

**Pull request merged**
