### PR TITLE
Implement OpenTracing Shim methods taking timestamp

### PR DESCRIPTION
**Pull request by malafeev**
Updates #3049

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
Thanks! Can you add unit tests for these methods?

**Comment by malafeev** [comment]
@anuraaga could you guide me how to do that? I didn't find the way to check span start/end time.

**Comment by jkwatson** [comment]
> @anuraaga could you guide me how to do that? I didn't find a way to check span start/end time.

You'll need to call `toSpanData()` on them and use the resulting SpanData to do those verifications, I think.

**Comment by carlosalberto** [comment]
We also need to implement the `Span.log()` overload taking a timestamp ;)

**Comment by malafeev** [comment]
@anuraaga I added tests
@carlosalberto I implemented log with timestamps

**Review by anuraaga — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
