### PR TITLE
Convert the export to use SpanData objects, rather than protobufs

### LINKED ISSUE #557: Change exporters to consume SpanData, rather then protobuf Spans

### PR DESCRIPTION
**Pull request by breedx-nr**
Resolves #557.

This ended up being a pretty sizable change (sorry!).  That protobuf class touched a lot of code.

### CODE REVIEW

**Comment by jkwatson** [comment]
The problem we faced is that as soon as you change the exporter API to emit `SpanData`, then you break the Jaeger & the InMemory exporters. We could certainly have a very small PR with just the `SpanData` in it, and additional methods on the `ReadableSpan`, but the next one is still going to be really big. I'm not sure how we can avoid big one. If you have ideas, we're all ears!

**Comment by bogdandrutu** [comment]
@jkwatson let's break it at least what we know is simple: first PR adds SpanData; Second PR will be the rest for the moment and we can decide how we can break more if we feel we need that.

**Comment by jkwatson** [comment]
Will do!

**Comment by jkwatson** [comment]
https://github.com/open-telemetry/opentelemetry-java/pull/567 just adds `SpanData`

**Comment by jkwatson** [comment]
The next step could be to add the methods needed to the `ReadableSpan` interface and implementation, as a separate PR.

**Comment by breedx-nr** [comment]
Agreed that we will do this more incrementally.  Closing this one.

**Pull request closed without merging**
